- README.md
Just an update to the documentation. Great project btw - nice, simple and then it's a pleasure to read the source code!
> Update doc for subscribing to all events

- lib/rails_event_store/repositories/event_repository.rb
Accompanying PR to https://github.com/arkency/ruby_event_store/pull/10
> Explicitly provide event_type

- .travis.yml
- Makefile
- rails_event_store.gemspec
- spec/full_story_spec.rb
Introducing mutation testing. Now it is time to kill some mutants.
> Let's mutate!

- SUMMARY.md
- docs/request_metadata.md
- docs/subscribe.md
* Added a section about intercepting metadata and configuring this behaviour.
* Updated documentation about subscriptions.
* Reorganized the structure of docs a little.
> Docs upgraded to 0.9

- Makefile
- spec/client_spec.rb
- spec/middleware_integration_spec.rb
- spec/middleware_spec.rb
- spec/request_metadata_spec.rb
- spec/support/test_rails.rb
Mutation coverage lowered, will check it later
> Killing mutants

- docs/projection.md
- docs/publish.md
- docs/read.md
In addition to https://github.com/arkency/rails_event_store/pull/51
> Adjusted documentation according to the new API with keyword args

- lib/rails_event_store/client.rb
- rails_event_store.gemspec
> Updated Ruby Event Store method calls according to the newer version

- docs/app.md
> fix(docs/app.md): Arrgegate -> Aggregate

- docs/install.html
> Fixed typo

- README.md
I just started using rails and was surprised to find a lively DDD community, and I couldn't believe it—that's awesome. Thanks for the work you've done in this space. I felt compelled to update the next DDD conf date.
> Updated next DDD workshop date.

- CONTRIBUTING.md
- LICENSE
- README.md
Moved LICENSE and CONTRIBUTING.md as well as these are common for the
whole project.
Changes:
- get rid of abandoned Gitter
- broken CodeClimate not included in this iteration
> Combined README for the project.

- aggregate_root/Gemfile
- aggregate_root/spec/spec_helper.rb
- rails_event_store/Gemfile
- rails_event_store/spec/spec_helper.rb
- rails_event_store_active_record/Gemfile
- rails_event_store_active_record/spec/spec_helper.rb
- ruby_event_store/Gemfile
- ruby_event_store/spec/spec_helper.rb
Related https://github.com/RailsEventStore/rails_event_store/issues/79
> Drop codeclimate-test-reporter

- Makefile
It should be useful locally to run all tests with a single command.
Synopsis:
make install # Installs dependencies
make test # Runs specs
make mutate # Runs specs and mutation tests
make # Shows help
I bet that the Makefile can be written more elegantly. Any tips are welcome
> Add a Makefile to run tests from all gems

- aggregate_root/CHANGELOG.md
- rails_event_store/CHANGELOG.md
- rails_event_store_active_record/CHANGELOG.md
- ruby_event_store/CHANGELOG.md
Indicate that file changelogs are no longer updated and where one can
find description of changes for new released.
> New location for grouped changelog.

- .travis.yml
* Run mutant on one (newest) Ruby version only
* https://github.com/RailsEventStore/rails_event_store/issues/83
* DB connection strings that we should test our code with
* https://github.com/RailsEventStore/aggregate_root/issues/8
* https://github.com/RailsEventStore/rails_event_store/pull/86
> Single mutation per ruby + DB connection string

- Makefile
Solution: automate it
Instead of manually rebase your branch with `RailsEventStore/rails_event_store` repository just run: `make rebase`.
It will:
* remove git remote `upstream`
* add git remote `upstream` with link to main repository
* fetch master `branch` from `upstream`
* rebase your current branch with fetched `upstream/master`
* displays current status - hashed of last commits in `upstream/master`, `origin/master` & `HEAD` of current branch
> Problem: some say fork rebase is hard

- aggregate_root/README.md
> Use a correct link to the docs

- rails_event_store-rspec/lib/rails_event_store/rspec/have_applied.rb
- rails_event_store-rspec/lib/rails_event_store/rspec/matchers.rb
- rails_event_store-rspec/spec/rails_event_store/rspec/have_applied_spec.rb
- rails_event_store-rspec/spec/rails_event_store/rspec/matchers_spec.rb
Moving PR proposed in old repository
> have_applied responds to failure message

- .travis.yml
> Run Ruby compatibility tests on sqlite.

- rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb
- rails_event_store_active_record/spec/event_repository_spec.rb
- ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb
> Events not persisted if stream append failed

- rails_event_store_active_record/lib/rails_event_store_active_record/generators/templates/v1_v2_migration_template.rb
and force developers to read instructions
* https://github.com/RailsEventStore/rails_event_store/issues/143
> Raise an exception by default in a migration

- ruby_event_store/Makefile
- ruby_event_store/lib/ruby_event_store/projection.rb
- ruby_event_store/spec/projection_spec.rb
> Fix projections again

- rails_event_store/lib/rails_event_store/active_job_dispatcher.rb
- rails_event_store/spec/active_job_dispatcher_spec.rb
> Handle after commit strategy in nested transactions in Rails 5

- rails_event_store/lib/rails_event_store.rb
- rails_event_store/lib/rails_event_store/all.rb
- rails_event_store/lib/rails_event_store/client.rb
- rails_event_store/spec/rails_event_store_spec.rb
- ruby_event_store/Makefile
- ruby_event_store/lib/ruby_event_store/client.rb
- ruby_event_store/spec/actions/create_events_in_stream_spec.rb
- ruby_event_store/spec/actions/delete_stream_events_spec.rb
- ruby_event_store/spec/actions/read_all_events_spec.rb
- ruby_event_store/spec/actions/read_all_streams_events_spec.rb
- ruby_event_store/spec/actions/read_events_batch_spec.rb
- ruby_event_store/spec/mappers/default_spec.rb
- ruby_event_store/spec/serialized_record_spec.rb
> Remove global for event repository config

- rails_event_store_active_record/Makefile
- rails_event_store_active_record/lib/rails_event_store_active_record/generators/migration_generator.rb
- rails_event_store_active_record/lib/rails_event_store_active_record/generators/v1_v2_migration_generator.rb
- rails_event_store_active_record/spec/no_warnings_spec.rb
- rails_event_store_active_record/spec/without_rails/Gemfile
- rails_event_store_active_record/spec/without_rails/runme.rb
- rails_event_store_active_record/spec/without_rails_spec.rb
`rails/generators` as optional dependency. Test of course is added.
> Allow using RES-AR without Rails

- .travis.yml
https://docs.travis-ci.com/user/caching#yarn-cache
https://github.com/RailsEventStore/rails_event_store/issues/263
> Experiment with Yarn cache.

- ruby_event_store/spec/subscription_spec.rb
Instead of spending a few seconds to concurrently publish events, we
orchestrate the threads using exchanger to make sure they publish events
when both threads are still subscribed locally.
Fixes: #254
> Faster test

- rails_event_store-browser/app/controllers/rails_event_store/browser/streams_controller.rb
- rails_event_store-browser/lib/rails_event_store/browser.rb
- rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb
- rails_event_store_active_record/lib/rails_event_store_active_record/event_repository_reader.rb
- rails_event_store_active_record/lib/rails_event_store_active_record/legacy_event_repository.rb
- rails_event_store_active_record/spec/event_repository_spec.rb
- rails_event_store_active_record/spec/legacy_event_repository_spec.rb
- rails_event_store_active_record/spec/spec_helper.rb
- ruby_event_store/lib/ruby_event_store/constants.rb
- ruby_event_store/lib/ruby_event_store/in_memory_repository.rb
- ruby_event_store/lib/ruby_event_store/specification.rb
- ruby_event_store/lib/ruby_event_store/stream.rb
- ruby_event_store/spec/in_memory_repository_spec.rb
- ruby_event_store/spec/spec_helper.rb
- ruby_event_store/spec/specification_spec.rb
- ruby_event_store/spec/stream_spec.rb
- ruby_event_store_rom_sql/lib/ruby_event_store/rom/event_repository.rb
- ruby_event_store_rom_sql/lib/ruby_event_store/rom/relations/stream_entries.rb
- ruby_event_store_rom_sql/lib/ruby_event_store/rom/repositories/stream_entries.rb
> GLOBAL_STREAM no longer a string

- ruby_event_store_rom_sql/Makefile
- ruby_event_store_rom_sql/lib/ruby_event_store/rom/event_repository.rb
- ruby_event_store_rom_sql/lib/ruby_event_store/rom/relations/stream_entries.rb
- ruby_event_store_rom_sql/lib/ruby_event_store/rom/repositories/events.rb
- ruby_event_store_rom_sql/lib/ruby_event_store/rom/repositories/stream_entries.rb
- ruby_event_store_rom_sql/lib/ruby_event_store/rom/unit_of_work.rb
- ruby_event_store_rom_sql/spec/rom/event_repository_spec.rb
Got Mutant passing 100%. Ignored methods with logic largely handling PostgreSQL-specific exceptions that would not be raised with SQLite.
> Fix ROM mutations

- ruby_event_store-rom/db/migrate/20180327044629_create_ruby_event_store_tables.rb
- ruby_event_store-rom/lib/ruby_event_store/rom.rb
- ruby_event_store-rom/lib/ruby_event_store/rom/adapters/sql/unit_of_work.rb
- ruby_event_store-rom/lib/ruby_event_store/rom/sql.rb
- ruby_event_store-rom/lib/ruby_event_store/rom/unit_of_work.rb
Addresses MySQL issues related to #302 and #303
> Fix MySQL tests

- bounded_context/lib/generators/bounded_context/bounded_context_generator.rb
- bounded_context/spec/generators_spec.rb
Add's .keep file into empty module folder of BC lib
> Better folder structure for BC

- ruby_event_store/lib/ruby_event_store/specification.rb
- ruby_event_store/spec/specification_spec.rb
> Immutable RES::Specifcation

- ruby_event_store/lib/ruby_event_store/batch_enumerator.rb
- ruby_event_store/lib/ruby_event_store/projection.rb
- ruby_event_store/lib/ruby_event_store/specification.rb
- ruby_event_store/spec/specification_spec.rb
Based on https://github.com/RailsEventStore/rails_event_store/issues/349#issuecomment-390182497
> Introduce #each_batch and #each for Batch API

- rails_event_store-rspec/lib/rails_event_store/rspec/have_applied.rb
- rails_event_store-rspec/lib/rails_event_store/rspec/have_published.rb
- rails_event_store-rspec/lib/rails_event_store/rspec/matchers.rb
- rails_event_store-rspec/spec/rails_event_store/rspec/have_applied_spec.rb
- rails_event_store-rspec/spec/rails_event_store/rspec/have_published_spec.rb
- rails_event_store-rspec/spec/rails_event_store/rspec/matchers_spec.rb
Ie:
`have_applied(FooEvent, BarEvent)` 
becomes 
`have published events that have to (be a FooEvent and be a BarEvent)`
> Add custom list phrasing of matchers for better description

- ruby_event_store/lib/ruby_event_store/client.rb
- ruby_event_store/spec/client_spec.rb
#346 & #347
If event triggers directly another event.
> Correlation between events in sync handlers

- aggregate_root/lib/aggregate_root.rb
- aggregate_root/spec/aggregate_root_spec.rb
- rails_event_store-browser/spec/api_spec.rb
- rails_event_store-browser/spec/ui_spec.rb
- rails_event_store-rspec/spec/rails_event_store/rspec/have_published_spec.rb
- rails_event_store-rspec/spec/rails_event_store/rspec/matchers_spec.rb
- rails_event_store/spec/client_spec.rb
- rails_event_store/spec/full_story_spec.rb
- rails_event_store/spec/middleware_integration_spec.rb
- rails_event_store/spec/protobuf_integration_spec.rb
- rails_event_store/spec/rails_event_store_spec.rb
- ruby_event_store/Makefile
- ruby_event_store/lib/ruby_event_store/client.rb
- ruby_event_store/spec/client_spec.rb
- ruby_event_store/spec/projection_spec.rb
- ruby_event_store/spec/subscription_spec.rb
> One publish method to rule them all [#366]

- railseventstore.org/source/community.html.md
* How to prepare a new pull request
* Licensing info
> Contributing guide docs

- rails_event_store-rspec/README.md
- railseventstore.org/source/docs/correlation_causation.html.md
- railseventstore.org/source/docs/exceptions.html.md.erb
- railseventstore.org/source/docs/expected_version.html.md
- railseventstore.org/source/docs/link.html.md.erb
- railseventstore.org/source/docs/mapping_serialization.html.md
- railseventstore.org/source/docs/projection.html.md
- railseventstore.org/source/docs/protobuf.html.md.erb
- railseventstore.org/source/docs/publish.html.md.erb
- railseventstore.org/source/docs/pubsub.html.md
- railseventstore.org/source/docs/request_metadata.html.md.erb
- railseventstore.org/source/docs/rspec.html.md.erb
- railseventstore.org/source/docs/subscribe.html.md.erb
- railseventstore.org/source/docs/without_rails.html.md
Should be deployed when #366 is released
[ci skip]
> Use new publish API in docs [#366]

- rails_event_store_active_record-legacy/spec/legacy_event_repository_spec.rb
- rails_event_store_active_record/spec/event_repository_spec.rb
- rails_event_store_active_record/spec/pg_linearized_event_repository_spec.rb
- rails_event_store_active_record/spec/v1_v2_schema_migration_spec.rb
- ruby_event_store-rom/lib/ruby_event_store/spec/rom/event_repository_lint.rb
- ruby_event_store-rom/spec/rom/adapters/sql/event_repository_spec.rb
- ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb
> Rename SRecord -> RubyEventStore::SRecord

- ruby_event_store/lib/ruby_event_store/specification.rb
- ruby_event_store/spec/projection_spec.rb
> Fix immutability in Specification results

- rails_event_store-browser/elm/elm-package.json
- rails_event_store-browser/elm/package.json
- rails_event_store-browser/elm/src/Main.elm
- rails_event_store-browser/elm/src/OpenedEventUI.elm
- rails_event_store-browser/elm/src/mocks/event.json
- rails_event_store-browser/elm/tests/Example.elm
- rails_event_store-browser/elm/tests/elm-package.json
- rails_event_store-browser/elm/yarn.lock
- rails_event_store-browser/spec/ui_spec.rb
> Make Browser display data and metadata in collapsable trees

- railseventstore.org/source/docs/rspec.html.md.erb
> Add missing documentation to `from` and `strict` rspec modifier

- railseventstore.org/source/docs/correlation_causation.html.md
Hey,
I noticed a small problem when I was reading the Correlation Causation Readme page. 
I think that it should be fine now.
Thanks,
Piotrek
> Correlation Causation readme fix

- rails_event_store_active_record-legacy/spec/legacy_event_repository_spec.rb
- rails_event_store_active_record/Makefile
- rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb
- rails_event_store_active_record/spec/event_repository_spec.rb
- rails_event_store_active_record/spec/pg_linearized_event_repository_spec.rb
- railseventstore.org/config.rb
- railseventstore.org/source/docs/migrating_messages.html.md
- railseventstore.org/source/partials/_documentation_nav.erb
- ruby_event_store-rom/lib/ruby_event_store/spec/rom/event_repository_lint.rb
- ruby_event_store/lib/ruby_event_store/client.rb
- ruby_event_store/lib/ruby_event_store/in_memory_repository.rb
- ruby_event_store/lib/ruby_event_store/instrumented_repository.rb
- ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb
- ruby_event_store/spec/client_spec.rb
- ruby_event_store/spec/in_memory_repository_spec.rb
- ruby_event_store/spec/instrumented_repository_spec.rb
> Changing messages

- rails_event_store_active_record-legacy/lib/rails_event_store_active_record/legacy/event_repository.rb
- rails_event_store_active_record-legacy/spec/legacy_event_repository_spec.rb
- rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb
- ruby_event_store-rom/lib/ruby_event_store/rom/event_repository.rb
- ruby_event_store/lib/ruby_event_store/client.rb
- ruby_event_store/lib/ruby_event_store/in_memory_repository.rb
- ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb
- ruby_event_store/spec/client_spec.rb
Any stream where event is stored or linked.
> Get list of streams of given event

- railseventstore.org/source/docs/subscribe.html.md
> Fix documentation issues

- railseventstore.org/source/docs/read.html.md
- railseventstore.org/source/partials/_documentation_nav.erb
- ruby_event_store/lib/ruby_event_store/specification.rb
> Describe read.event API

- rails_event_store_active_record-legacy/lib/rails_event_store_active_record/legacy/event_repository.rb
- rails_event_store_active_record-legacy/lib/rails_event_store_active_record/legacy/generators/templates/v1_v2_migration_template.rb
- rails_event_store_active_record/Makefile
- rails_event_store_active_record/lib/rails_event_store_active_record.rb
- rails_event_store_active_record/lib/rails_event_store_active_record/event_repository_reader.rb
- rails_event_store_active_record/lib/rails_event_store_active_record/generators/index_by_event_type_generator.rb
- rails_event_store_active_record/lib/rails_event_store_active_record/generators/templates/index_by_event_type_template.rb
- rails_event_store_active_record/lib/rails_event_store_active_record/generators/templates/migration_template.rb
- rails_event_store_active_record/spec/before_index_by_event_type/Gemfile
- rails_event_store_active_record/spec/before_index_by_event_type/fill_data.rb
- rails_event_store_active_record/spec/index_by_event_type_generator_spec.rb
- rails_event_store_active_record/spec/index_by_event_type_migration_spec.rb
- ruby_event_store-rom/db/migrate/20181026152045_index_by_event_type.rb
- ruby_event_store-rom/lib/ruby_event_store/rom/adapters/memory/relations/stream_entries.rb
- ruby_event_store-rom/lib/ruby_event_store/rom/adapters/sql/relations/stream_entries.rb
- ruby_event_store-rom/lib/ruby_event_store/rom/repositories/events.rb
- ruby_event_store/lib/ruby_event_store/in_memory_repository.rb
- ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb
- ruby_event_store/lib/ruby_event_store/specification.rb
- ruby_event_store/lib/ruby_event_store/specification_result.rb
- ruby_event_store/spec/specification_spec.rb
> Filtering by event types

- railseventstore.org/source/docs/publish.html.md
I'm enjoying reading through these docs. I noticed this and wanted to reach out.
> Adds missing word to publish.html.md

- ruby_event_store/lib/ruby_event_store/spec/event_lint.rb
- ruby_event_store/spec/event_spec.rb
> Minimal linter for Event classes

- railseventstore.org/source/docs/gdpr.html.md
@pawelpacana made some edits for you to approve.
> Some minor copy edits

- lib/Dockerfile.2_4
- lib/Dockerfile.2_5
- lib/Dockerfile.2_6
- rails_event_store_active_record/rails_event_store_active_record.gemspec
- rails_event_store_active_record/spec/event_repository_spec.rb
- rails_event_store_active_record/spec/without_rails_spec.rb
> Updating messages with sqlite

- aggregate_root/lib/aggregate_root.rb
- aggregate_root/lib/aggregate_root/default_apply_strategy.rb
> AggregateRoot + Protobuf

- support/bundler/Gemfile.shared
> Bump mutant.

- ruby_event_store-browser/elm/src/Main.elm
- ruby_event_store-browser/lib/ruby_event_store/browser/app.rb
- ruby_event_store-browser/spec/api_spec.rb
- ruby_event_store-browser/spec/support/json_api_lint.rb
> Handle the case in browser when event is missing

- rails_event_store_active_record/lib/rails_event_store_active_record/generators/migration_generator.rb
- rails_event_store_active_record/lib/rails_event_store_active_record/generators/templates/create_event_store_events_template.rb
- rails_event_store_active_record/spec/migration_generator_spec.rb
- railseventstore.org/source/docs/mapping_serialization.html.md
- support/helpers/migrator.rb
This is a follow up PR to https://github.com/RailsEventStore/rails_event_store/issues/592
> Support JSON data types in ActiveRecord DB Migration

- railseventstore.org/source/docs/read.html.md.erb
> Fix example in documentation

- ruby_event_store-browser/elm/src/Page/ShowEvent.elm
> Fix stream links and parent event link

- ruby_event_store-browser/elm/src/Layout.elm
For a long time, we do have a stream browser link which does not do anything.
> Remove stream browser link

- .circleci/config.rb
- .circleci/config.yml
- support/docker/Dockerfile.2_4
- support/docker/Dockerfile.2_5
- support/docker/Dockerfile.2_6
- support/docker/Dockerfile.2_7
- support/helpers/protobuf_helper.rb
> Ruby 2.7 becomes current_ruby

- railseventstore.org/source/docs/browser.html.md
add color syntax and fix test for rails installation
> Update browser docs

- support/bundler/Gemfile.shared
- support/make/mutant.mk
https://github.com/mbj/mutant/blob/master/Changelog.md#v0101-2020-10-29
> Mutant 0.10

- aggregate_root/Gemfile.lock
- bounded_context/Gemfile.lock
- rails_event_store/Gemfile.lock
- rails_event_store_active_record/Gemfile.lock
- ruby_event_store-browser/Gemfile.lock
- ruby_event_store-rom/Gemfile.lock
- ruby_event_store/Gemfile.lock
- support/bundler/Gemfile.shared
* incremental mode works correctly with this one
> Up-to-date mutant

- aggregate_root/Gemfile
- aggregate_root/Gemfile.lock
- bounded_context/Gemfile
- bounded_context/Gemfile.rails_5_0
- bounded_context/Gemfile.rails_5_1
- bounded_context/Gemfile.rails_5_2
- rails_event_store-rspec/Gemfile
- rails_event_store-rspec/Gemfile.rails_5_0
- rails_event_store-rspec/Gemfile.rails_5_1
- rails_event_store-rspec/Gemfile.rails_5_2
- rails_event_store/Gemfile
- rails_event_store/Gemfile.lock
- rails_event_store/Gemfile.rails_5_0
- rails_event_store/Gemfile.rails_5_1
- rails_event_store/Gemfile.rails_5_2
- rails_event_store_active_record/Gemfile
- rails_event_store_active_record/Gemfile.rails_5_0
- rails_event_store_active_record/Gemfile.rails_5_1
- rails_event_store_active_record/Gemfile.rails_5_2
- ruby_event_store-browser/Gemfile
- ruby_event_store-rom/Gemfile
- ruby_event_store/Gemfile
- support/bundler/Gemfile.shared
https://github.com/RailsEventStore/rails_event_store/pull/860#issuecomment-739939397
> Second life for shared Gemfile concept 

- .github/workflows/coverage.yml
- .github/workflows/ruby_event_store-rom.yml
> Make it five o'clock kind of event

- .github/workflows/rails_event_store_active_record.yml
This took 6 minutes in rspec:
https://github.com/RailsEventStore/rails_event_store/runs/1521359777?check_suite_focus=true
This took ~17 seconds rspec:
https://github.com/RailsEventStore/rails_event_store/runs/1521279785?check_suite_focus=true
WTAF?
> Revert slowness

- .github/workflows/aggregate_root.yml
- .github/workflows/bounded_context.yml
- .github/workflows/rails_event_store-rspec.yml
- .github/workflows/rails_event_store.yml
- .github/workflows/rails_event_store_active_record.yml
- .github/workflows/ruby_event_store-browser.yml
- .github/workflows/ruby_event_store-rom.yml
- .github/workflows/ruby_event_store.yml
- netlify.toml
> No code builds for docs and site

- aggregate_root/Gemfile.lock
- bounded_context/Gemfile.lock
- bounded_context/Gemfile.rails_5_0.lock
- bounded_context/Gemfile.rails_5_1.lock
- bounded_context/Gemfile.rails_5_2.lock
- bounded_context/Gemfile.rails_6_0.lock
- contrib/ruby_event_store-outbox/Gemfile.lock
- contrib/ruby_event_store-outbox/Gemfile.rails_5_2.lock
- contrib/ruby_event_store-outbox/Gemfile.rails_6_0.lock
- rails_event_store/Gemfile.lock
- rails_event_store/Gemfile.rails_5_0.lock
- rails_event_store/Gemfile.rails_5_1.lock
- rails_event_store/Gemfile.rails_5_2.lock
- rails_event_store/Gemfile.rails_6_0.lock
- rails_event_store_active_record/Gemfile.lock
- rails_event_store_active_record/Gemfile.rails_5_0.lock
- rails_event_store_active_record/Gemfile.rails_5_1.lock
- rails_event_store_active_record/Gemfile.rails_5_2.lock
- rails_event_store_active_record/Gemfile.rails_6_0.lock
- ruby_event_store-browser/Gemfile.lock
- ruby_event_store-rom/Gemfile.lock
- ruby_event_store-rspec/Gemfile.lock
- ruby_event_store/Gemfile.lock
- support/bundler/Gemfile.shared
See: https://github.com/mbj/mutant/blob/master/Changelog.md#v01020-2020-12-16
TLDR: It may be much faster on your big passes.
> Upgrade to mutant-0.10.20

- ruby_event_store-browser/lib/ruby_event_store/browser/json_api_event.rb
- ruby_event_store-rspec/spec/spec_helper.rb
- ruby_event_store/Makefile
- ruby_event_store/lib/ruby_event_store/event.rb
- ruby_event_store/lib/ruby_event_store/mappers/transformation/domain_event.rb
- ruby_event_store/spec/event_spec.rb
- ruby_event_store/spec/mappers/default_spec.rb
- ruby_event_store/spec/mappers/encryption_mapper_spec.rb
- ruby_event_store/spec/mappers/null_mapper_spec.rb
- ruby_event_store/spec/mappers/protobuf_spec.rb
- ruby_event_store/spec/mappers/transformation/proto_event_spec.rb
Remove timestamp & valid_at methods from domain event.
> Reduce Event API

- rails_event_store_active_record/Makefile
- rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb
- rails_event_store_active_record/lib/rails_event_store_active_record/index_violation_detector.rb
- Optimize allocations
- Index violation detection aware of chosen table names
> Parametrized IndexViolationDetector

- aggregate_root/Gemfile.lock
- aggregate_root/aggregate_root.gemspec
- aggregate_root/lib/aggregate_root.rb
- aggregate_root/spec/aggregate_root_spec.rb
- rails_event_store/Gemfile.lock
- rails_event_store/Gemfile.rails_5_0.lock
- rails_event_store/Gemfile.rails_5_1.lock
- rails_event_store/Gemfile.rails_5_2.lock
- rails_event_store/Gemfile.rails_6_0.lock
- rails_event_store/spec/dummy_5_0/Gemfile.lock
- rails_event_store/spec/dummy_5_1/Gemfile.lock
- rails_event_store/spec/dummy_5_2/Gemfile.lock
- rails_event_store/spec/dummy_6_0/Gemfile.lock
- rails_event_store/spec/dummy_6_1/Gemfile.lock
- ruby_event_store-rspec/Gemfile.lock
Includes failing tests cases for #962 with Ruby 3.0
> Make no assumptions for aggregate root initializer

- contrib/minitest-ruby_event_store/Gemfile
- contrib/minitest-ruby_event_store/Gemfile.lock
- contrib/minitest-ruby_event_store/test/minitest/ruby_event_store_test.rb
- contrib/minitest-ruby_event_store/test/test_helper.rb
- contrib/ruby_event_store-profiler/lib/ruby_event_store/profiler.rb
- contrib/ruby_event_store-transformations/Gemfile
- contrib/ruby_event_store-transformations/Gemfile.lock
- contrib/ruby_event_store-transformations/lib/ruby_event_store/transformations.rb
- contrib/ruby_event_store-transformations/lib/ruby_event_store/transformations/identity_map.rb
- contrib/ruby_event_store-transformations/lib/ruby_event_store/transformations/with_indifferent_access.rb
- contrib/ruby_event_store-transformations/ruby_event_store-transformations.gemspec
- contrib/ruby_event_store-transformations/spec/identity_map_spec.rb
- contrib/ruby_event_store-transformations/spec/spec_helper.rb
- contrib/ruby_event_store-transformations/spec/with_indifferent_access_spec.rb
- ruby_event_store-rspec/Gemfile
- ruby_event_store-rspec/Gemfile.lock
- ruby_event_store-rspec/spec/ruby_event_store/rspec/have_published_spec.rb
- ruby_event_store-rspec/spec/ruby_event_store/rspec/have_subscribed_to_events_spec.rb
- ruby_event_store-rspec/spec/ruby_event_store/rspec/publish_spec.rb
- ruby_event_store-rspec/spec/spec_helper.rb
> Extract IdentityMap transformation

- .github/workflows/ruby_event_store-sidekiq_scheduler.yml
- .github/workflows/ruby_event_store-sidekiq_scheduler_coverage.yml
- contrib/ruby_event_store-sidekiq_scheduler/.mutant.yml
- contrib/ruby_event_store-sidekiq_scheduler/Gemfile
- contrib/ruby_event_store-sidekiq_scheduler/Gemfile.lock
- contrib/ruby_event_store-sidekiq_scheduler/Gemfile.sidekiq_5
- contrib/ruby_event_store-sidekiq_scheduler/Gemfile.sidekiq_5.lock
- contrib/ruby_event_store-sidekiq_scheduler/Makefile
- contrib/ruby_event_store-sidekiq_scheduler/README.md
- contrib/ruby_event_store-sidekiq_scheduler/lib/ruby_event_store/sidekiq_scheduler.rb
- contrib/ruby_event_store-sidekiq_scheduler/lib/ruby_event_store/sidekiq_scheduler/version.rb
- contrib/ruby_event_store-sidekiq_scheduler/ruby_event_store-sidekiq_scheduler.gemspec
- contrib/ruby_event_store-sidekiq_scheduler/spec/no_warnings_spec.rb
- contrib/ruby_event_store-sidekiq_scheduler/spec/sidekiq_scheduler_spec.rb
- contrib/ruby_event_store-sidekiq_scheduler/spec/spec_helper.rb
Add a `RubyEventStore::SidekiqScheduler` for the ones that use directly Sidekiq, not ActiveJob
> Add ruby_event_store-sidekiq_scheduler

- rails_event_store_active_record/lib/rails_event_store_active_record/event_repository_reader.rb
- rails_event_store_active_record/spec/event_repository_spec.rb
- ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb
> Bi-temporal queries and batches

- railseventstore.org/source/docs/v2/subscribe.html.md
Remove unnecessary `to:`, as per source code.
> docs(client): fix subscribe_to_all_events

- aggregate_root/aggregate_root.gemspec
- contrib/minitest-ruby_event_store/minitest-ruby_event_store.gemspec
- contrib/ruby_event_store-flipper/ruby_event_store-flipper.gemspec
- contrib/ruby_event_store-newrelic/ruby_event_store-newrelic.gemspec
- contrib/ruby_event_store-outbox/ruby_event_store-outbox.gemspec
- contrib/ruby_event_store-profiler/ruby_event_store-profiler.gemspec
- contrib/ruby_event_store-protobuf/ruby_event_store-protobuf.gemspec
- contrib/ruby_event_store-rom/ruby_event_store-rom.gemspec
- contrib/ruby_event_store-sidekiq_scheduler/ruby_event_store-sidekiq_scheduler.gemspec
- contrib/ruby_event_store-transformations/ruby_event_store-transformations.gemspec
- rails_event_store/rails_event_store.gemspec
- rails_event_store_active_record/rails_event_store_active_record.gemspec
- ruby_event_store-browser/ruby_event_store-browser.gemspec
- ruby_event_store-rspec/ruby_event_store-rspec.gemspec
- ruby_event_store/ruby_event_store.gemspec
Read more: https://guides.rubygems.org/mfa-requirement-opt-in/
> Require MFA for releases

- railseventstore.org/source/docs/v2/gdpr.html.md
This fixes TypeError "no implicit conversion of nil into Hash" exception
> Fix request_metadata lambda example in docs

- ruby_event_store/lib/ruby_event_store/client.rb
- ruby_event_store/spec/client_spec.rb
> Raise ArgumentError when trying to publish nil as event

- railseventstore.org/source/layouts/base.erb
- railseventstore.org/source/layouts/documentation.erb
- railseventstore.org/source/layouts/landing.erb
- railseventstore.org/source/layouts/layout.erb
- railseventstore.org/source/partials/_anchorjs.erb
- railseventstore.org/source/partials/_doc_search.erb
- railseventstore.org/source/partials/_doc_search_top.erb
- railseventstore.org/source/partials/_hero.erb
- railseventstore.org/source/partials/_site_footer.erb
- railseventstore.org/source/partials/_site_navigation.erb
- railseventstore.org/source/partials/_version_redirect.erb
* structure emerges visibly
* temporal base layout duplication is gone
> Refactor with partials

- ruby_event_store/lib/ruby_event_store/projection.rb
- ruby_event_store/spec/projection_spec.rb
Proposition of changes based on discussion we had during review of previous PR
> Projections re re design

- rails_event_store/spec/rails_foreign_key_on_event_id_migration_generator_spec.rb
- ruby_event_store-active_record/lib/ruby_event_store/active_record/generators/foreign_key_on_event_id_migration_generator.rb
- ruby_event_store-active_record/lib/ruby_event_store/active_record/generators/rails_foreign_key_on_event_id_migration_generator.rb
- ruby_event_store-active_record/lib/ruby_event_store/active_record/generators/templates/template_directory.rb
- ruby_event_store-active_record/lib/ruby_event_store/active_record/generators/verify_adapter.rb
- ruby_event_store-active_record/spec/foreign_key_on_event_id_migration_generator_spec.rb
- ruby_event_store-active_record/spec/template_directory_spec.rb
- ruby_event_store-active_record/spec/verify_data_type_for_adapter_spec.rb
Addressing issue [#1650]
- ~[ ] add postgres integration run with `postgis` adapter used?~
> postgis support

- .github/workflows/aggregate_root.yml
- .github/workflows/dres_client.yml
- .github/workflows/dres_rails.yml
- .github/workflows/minitest-ruby_event_store.yml
- .github/workflows/rails_event_store.yml
- .github/workflows/ruby_event_store-active_record.yml
- .github/workflows/ruby_event_store-browser.yml
- .github/workflows/ruby_event_store-flipper.yml
- .github/workflows/ruby_event_store-newrelic.yml
- .github/workflows/ruby_event_store-outbox.yml
- .github/workflows/ruby_event_store-profiler.yml
- .github/workflows/ruby_event_store-protobuf.yml
- .github/workflows/ruby_event_store-rom.yml
- .github/workflows/ruby_event_store-rspec.yml
- .github/workflows/ruby_event_store-sequel.yml
- .github/workflows/ruby_event_store-sidekiq_scheduler.yml
- .github/workflows/ruby_event_store-transformations.yml
- .github/workflows/ruby_event_store.yml
- support/ci/generate
- Drop testing on EOL Ruby 6 months later
- Let join deduplicate matrix items
> Drop Ruby 2.7

- .github/workflows/aggregate_root.yml
- .github/workflows/rails_event_store.yml
- .github/workflows/ruby_event_store-active_record.yml
- .github/workflows/ruby_event_store-browser.yml
- .github/workflows/ruby_event_store-rspec.yml
- .github/workflows/ruby_event_store.yml
- support/ci/db.yaml.erb
- support/ci/elm.yaml.erb
- support/ci/ruby.yaml.erb
Better assesment of what triggers the workflow.
> Transition to paths instead of paths-ignore trigger

- .github/workflows/dres_rails.yml
- .github/workflows/ruby_event_store-active_record.yml
- .github/workflows/ruby_event_store-rom.yml
- .github/workflows/ruby_event_store-sequel.yml
- support/ci/db.yaml.erb
- support/ci/dres_rails.yaml.erb
- support/ci/generate
- support/ci/rom.yaml.erb
Co-authored-by: Szymon Fiedler <szymon.fiedler@gmail.com>
Co-authored-by: Piotr Jurewicz <pjurewicz93@gmail.com>
> Test on newest and the oldest supported PostgreSQL versions

- railseventstore.org/source/docs/v2/backwards_compatibility.html.md
- railseventstore.org/source/docs/v2/maintenance_policy.html.md
- railseventstore.org/source/partials/_documentation_nav_v2.erb
> Add article about backwards compatibility

- railseventstore.org/source/docs/v2/start.html.md
This PR simply aims to fix a small typo on Introduction page
> docs(start): fix typo about provided word

- railseventstore.org/docs/advanced-topics/event-serialization-formats.md
Saw the open issue, thought I would offer a PR for it since I went through a similar process integrating the library.
Caught an unrelated spelling error and reworded a sentence I thought was little odd but would revert that if you preferred the original phrasing.
> Closes #1681. JSON client in serialization docs

- .streerc
- contrib/ruby_event_store-rom/lib/ruby_event_store/rom/relations/stream_entries.rb
- ruby_event_store-active_record/lib/ruby_event_store/active_record/event.rb
- ruby_event_store/lib/ruby_event_store/in_memory_repository.rb
- **Ternary operator is fine**
- **Re-format**
> ternary is fine

- rails_event_store/.mutant.yml
- rails_event_store/Gemfile
- rails_event_store/Gemfile.lock
- rails_event_store/Gemfile.rails_7_1
- rails_event_store/Gemfile.rails_7_1.lock
- rails_event_store/Gemfile.rails_7_2
- rails_event_store/Gemfile.rails_7_2.lock
- rails_event_store/spec/active_job_scheduler_spec.rb
- rails_event_store/spec/async_handler_helpers_spec.rb
- **Missing serializer for verification**
- **We're not testing how well ActiveJob integrates with its adapters**
We should only verify that ActiveJob contract is satisfied.
- **This test is pointless too**
- **Refactor**
- **Simpler**
- **Refactor expectation**
- **One callback**
- **Refactor**
- **Refactor**
- **Move around**
- **Fancy API**
- **Refactor**
- **Improve handler factories**
- **Refactor**
> Refactor spec

- ruby_event_store-active_record/spec/transactions_spec.rb
* RES uses transaction in order to have consistent and atomic inserts into both
`event_store_events` and `event_store_events_in_streams tables` — from
that POV it doesn't matter whether it is or not a sub-transaction
(the one with requires_new: true), both work equally good
* there might be conflicts on database contraints — `event_id` uniquness
in `event_store_events` or stream position conflict in
`event_store_events_in_streams` (i.e. `expected_version: :none`),
these conflicts would make transaction (or just a sub-transaction of
the transaction) aborted and further unusable
* there's a pattern to append events uniquely, avoiding race condition:
https://railseventstore.org/docs/common-usage-patterns/publishing_unique_events/
- this pattern is useful in at-least-once situations
- with …
> Explain clearly the only reason why we need a sub-transaction (SAVEPOINT)
