RailsEventStore/rails_event_store

lib/rails_event_store.rb, lib/rails_event_store/event_entity.rb, lib/rails_event_store/models/event.rb, lib/rails_event_store/repositories/event_repository.rb, rails_event_store.gemspec, spec/event_repository_spec.rb
Adds an explicit dependency on `activemodel`. Basically my mid-term goal is to build the `mongoid` adapter so I figured I should first start by refactoring how the repository pattern was applied here.
Thoughts and comments are welcome
=> fix: apply repository pattern correctly by decoupling event entity from any ORM

lib/rails_event_store/repositories/event_repository.rb
Rails doesn't seem to support `find(:all)` anymore, so I propose this fix.
How would you prefer this to be tested?
=> Use supported Rails methods for finding all events

Gemfile, README.md, lib/rails_event_store/event_handlers/slack_event_handler.rb, lib/rails_event_store/repositories/event_repository.rb, rails_event_store.gemspec, spec/example_invoicing_app.rb, spec/full_story_spec.rb
The newest Ruby Event Store changed how event subscription work.
Currently event types are used rather than strings
currently:
```ruby
es.subscribe(Handler, [OrderCreated])
```
before:
```ruby
es.subscribe(Handler, ['OrderCreated'])
```
This commit makes RES work with the new approach.
=> Make RES compatible with the newest Ruby Event Store

lib/rails_event_store/client.rb, spec/client_spec.rb
Just delegated methods responsible for reading events backward
to the repository.
=> Allow to read events backward

lib/rails_event_store.rb, lib/rails_event_store/client.rb, lib/rails_event_store/middleware.rb, lib/rails_event_store/railtie.rb, rails_event_store.gemspec, spec/request_metadata_spec.rb
The idea behind it is to automatically record some data not directly related to particular
event but useful in context of audit log.
What (if anything) to be recorded can be made confifgurable,I wanted to deliver working prototype first.
Possbily interesting stuff to record:
- user agent
- request id (i.e. to use as a correlation id for group of events)
- logged in user identifier (with help of some popular solutions like Devise)
=> Rails request details in event metadata.

docs/publish.md
rebuilt docs with a newer version of gitbook, served it locally and it looks fine
=> Fixed naming clash in examples provided on the publish page

Makefile, lib/rails_event_store/middleware.rb
- would not work, I've mistakenly removed following code previously:
status, headers, body = @app.call(env)
return status, headers, body
- there are no after actions which could raise exception after body is
set
- if body is not set, that's no-op
=> Useless safety measure.

docs/subscribe.md
`subscirbe_to_all_events` to `subscribe_to_all_events`
=> Fix typo with event_store.subscribe_to_all_events

lib/rails_event_store.rb, lib/rails_event_store/all.rb, lib/rails_event_store/client.rb, lib/rails_event_store/repository.rb, spec/client_spec.rb, spec/repository_spec.rb
By default it will use the active_record event repository. If you want to
use another event repository without loading unecessary active_record
dependency, you'll need to do:
```
gem 'rails_event_store', require: false
gem 'rails_event_store_mongoid'
```
Then require manually `rails_event_store` gem dy doing:
```
require 'rails_event_store/all'
```
This will prevent loading `rails_event_store_active_record` gem by default.
Finally, specify the event repository adapter with:
```
RailsEventStore::Repository.adapter = :mongoid
```
It will look for a class named `RailsEventStoreMongoid::EventRepository`
@mpraglowski I was not able to kill the last mutant. Can you give me a hand?
```
RailsEventStore::Repository.adapter=:/Users/gottfrois/Code/rails_event_store/lib/rails_event_store/repository.rb …
```
=> Allows to set the event repository used.

lib/rails_event_store.rb, lib/rails_event_store/all.rb
The event repository initialization must happen inside `all.rb` since on other repo (mongoid for example) we don't require `rails_event_store.rb` but only `rails_event_store/all.rb`
=> Fixes where is initialized event repository

lib/rails_event_store/all.rb, lib/rails_event_store/railtie.rb
Otherwise the rack middleware is not added to the Rails stack
and events are not enriched with request metadata.
=> Require the railtie

ruby_event_store/lib/ruby_event_store/pub_sub/broker.rb, ruby_event_store/lib/ruby_event_store/pub_sub/dispatcher.rb, ruby_event_store/lib/ruby_event_store/spec/dispatcher_lint.rb, ruby_event_store/lib/ruby_event_store/spec/event_broker_lint.rb, ruby_event_store/spec/subscription_spec.rb
Solution: Move check if handler fulfills a contract from execution to subscription
Excessive check if handler fullfils a contract (define `call` method) on each
handler call should be avoided. Instead of check on execution it will be
checked when handler's subscription is defined.
=> Problem: excessive check if handler fulfils a contract at execution

aggregate_root/Gemfile, rails_event_store/Gemfile, rails_event_store_active_record/Gemfile
Currently rails_event_store uses released versions of ruby_event_store
and rails_event_store_active_record. This is inconvenient for
development and testing.
Thanks to this patch rails_event_store will use local dependencies from the repo.
It allows to change ruby_event_store and quickly test how the change affects
rails_event_store.
Also the CI will run the entire test suite with the most recent dependencies
rather than with the released ones.
=> Use local dependencies

rails_event_store/spec/request_metadata_spec.rb, rails_event_store_active_record/.rspec, rails_event_store_active_record/spec/migration_generator_spec.rb
```
Running basic tests - beware: this won't guarantee build pass
...........
Finished in 0.01105 seconds (files took 0.14375 seconds to load)
11 examples, 0 failures
Running basic tests - beware: this won't guarantee build pass
...........................................................................................................
Finished in 0.04064 seconds (files took 0.13198 seconds to load)
107 examples, 0 failures
Running basic tests - beware: this won't guarantee build pass
/Users/pawel/Code/rails_event_store/rails_event_store/spec/request_metadata_spec.rb:5: warning: already initialized constant RailsEventStore::DummyEvent
/Users/pawel/Code/rails_event_store/rails_event_store/spec/middleware_integration_spec.rb:8: warning: previous definition of DummyEvent was here …
```
=> Cleaner output of top-level tests.

aggregate_root/lib/aggregate_root.rb, aggregate_root/spec/aggregate_root_spec.rb
that makes testing much easier when commands are used to build state.
Developers can easily opt-out by doing
```ruby
def apply(*events)
super
nil
end
```
in their class.
or by explicitly returning `nil` or `self`
```ruby
def supply(quantity)
raise NotRegistered unless @store_id
apply(ProductSupplied.new(data: {
store_id: @store_id,
sku: @sku,
quantity: quantity,
}))
nil
end
```
=> apply returns applied events

aggregate_root/lib/aggregate_root.rb, aggregate_root/spec/aggregate_root_spec.rb, aggregate_root/spec/spec_helper.rb
Instead of https://github.com/RailsEventStore/rails_event_store/pull/108
=> Make unpublished_events public and read-only

rails_event_store/lib/rails_event_store/active_job_dispatcher.rb, rails_event_store/lib/rails_event_store/all.rb, rails_event_store/rails_event_store.gemspec, rails_event_store/spec/active_job_dispatcher_spec.rb, ruby_event_store/lib/ruby_event_store/client.rb, ruby_event_store/lib/ruby_event_store/errors.rb, ruby_event_store/lib/ruby_event_store/pub_sub/broker.rb, ruby_event_store/lib/ruby_event_store/pub_sub/dispatcher.rb, ruby_event_store/lib/ruby_event_store/spec/dispatcher_lint.rb, ruby_event_store/lib/ruby_event_store/spec/event_broker_lint.rb, ruby_event_store/spec/client_spec.rb, ruby_event_store/spec/subscription_spec.rb
Solution: ActiveJob dispatcher and a new way of subscribing to domain events
`ActiveJobDispatcher` is a new dispatcher ready to use with RES as a replacement of `DefaultDispatcher`.
The main improvement is that if a handler class is an ancestor of `ActiveJob::Base` it will be handled asynchronously.
Also it defines a set of `ActiveJob` adapters for which enqueue of tasks to perform (handlers) need to be done only after transaction is committed.
The new way of subscribing to domain events:
- currently we have `subscribe(lambda_or_callable_class_instance, [domain_event], unsubscribe_proc)`, this will not allow us to use async jobs as we need to pass instance to RES client
- adding 2 new methods:
- `on([domain_event], class_name, unsubscribe_proc)` and `on_all_events(class_name, …
=> Problem: only sync handlers are possible

rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb, rails_event_store_active_record/spec/event_repository_spec.rb, ruby_event_store/lib/ruby_event_store/in_memory_repository.rb, ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb
- addresses https://github.com/RailsEventStore/rails_event_store/issues/131
- no changes to migration in https://github.com/RailsEventStore/rails_event_store/issues/129, it might be slightly different if we decide on https://github.com/RailsEventStore/rails_event_store/issues/131#issuecomment-335634991
=> Remove redundant "__global__" stream, slightly changing "all" semantics

.travis.yml, rails_event_store/Gemfile, rails_event_store/Makefile, rails_event_store/lib/rails_event_store/active_job_dispatcher.rb
When transaction is rolled back AR calls `rollback!` on all records
added to transaction. The methods, even withou aby body, need to be
defined to avoid missing method error.
Fix for https://github.com/RailsEventStore/rails_event_store/issues/132
=> Add missing methods to AsyncRecord

CONTRIBUTING.md, README.md, RELEASE.md, aggregate_root/README.md, bounded_context/spec/dummy_4_2_10/config/locales/en.yml, bounded_context/spec/dummy_5_0_6/config/locales/en.yml, bounded_context/spec/dummy_5_0_6/config/routes.rb, bounded_context/spec/dummy_5_1_4/config/locales/en.yml, bounded_context/spec/dummy_5_1_4/config/routes.rb, rails_event_store-rspec/README.md, rails_event_store/CHANGELOG.md, rails_event_store/rails_event_store.gemspec, rails_event_store_active_record/README.md, rails_event_store_active_record/lib/rails_event_store_active_record/generators/templates/v1_v2_migration_template.rb, rails_event_store_active_record/rails_event_store_active_record.gemspec, ruby_event_store/ruby_event_store.gemspec
- another change: in 2017 we should avoid http (without s) everywhere where it's possible
=> Make all the repo links to lead to RailsEventStore org

ruby_event_store/lib/ruby_event_store/projection.rb, ruby_event_store/spec/projection_spec.rb
There are the cases when it is needed to use one handler for many events
within RubyEventStore::Projection.
Passing array of events to #when method we can rewrite this:
```
Projection.
from_stream(stream_name).
init( -> { { total: 0 } }).
when(MoneyDeposited, ->(state, event) { state[:total] += event.data[:amount] }).
when(MoneyWithdrawn, ->(state, event) { state[:total] += event.data[:amount] }).
run(event_store)
```
to this:
```
Projection.
from_stream(stream_name).
init( -> { { total: 0 } }).
when([MoneyDeposited, MoneyWithdrawn], ->(state, event) { state[:total] += event.data[:amount] }).
run(event_store)
```
=> Add RubyEventStore#when_any_of method

rails_event_store_active_record/Makefile, rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb, rails_event_store_active_record/lib/rails_event_store_active_record/legacy_event_repository.rb, rails_event_store_active_record/spec/event_repository_spec.rb, rails_event_store_active_record/spec/legacy_event_repository_spec.rb, ruby_event_store/lib/ruby_event_store/client.rb, ruby_event_store/lib/ruby_event_store/errors.rb, ruby_event_store/lib/ruby_event_store/in_memory_repository.rb, ruby_event_store/lib/ruby_event_store/mappers/default.rb, ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb, ruby_event_store/spec/actions/read_events_batch_spec.rb, ruby_event_store/spec/client_spec.rb, ruby_event_store/spec/in_memory_repository_spec.rb
Implements API for linking events to streams #134 
* does not trigger handlers
* verifies uniqueness of linked event in a stream
* verifies existence of linked event
=> link_to_stream

rails_event_store/spec/full_story_spec.rb, ruby_event_store/Makefile, ruby_event_store/lib/ruby_event_store/client.rb, ruby_event_store/lib/ruby_event_store/in_memory_repository.rb, ruby_event_store/lib/ruby_event_store/pub_sub/broker.rb, ruby_event_store/lib/ruby_event_store/spec/event_broker_lint.rb, ruby_event_store/ruby_event_store.gemspec, ruby_event_store/spec/client_spec.rb, ruby_event_store/spec/in_memory_repository_spec.rb, ruby_event_store/spec/projection_spec.rb, ruby_event_store/spec/subscription_spec.rb, ruby_event_store/spec/within_spec.rb
=> PoC - new and safe dynamic subscriptions API - discussion

aggregate_root/lib/aggregate_root.rb, aggregate_root/lib/aggregate_root/default_apply_strategy.rb, aggregate_root/spec/aggregate_root_spec.rb, aggregate_root/spec/spec_helper.rb
I would like to introduce second way of declaring event handler methods on aggregate:
```ruby
on OrderCreated do |_event|
@status = :created
end
```
which will generate standard private handler method:
```ruby
def apply_order_created(_event)
@status = :created
end
```
Full example of usage (include of Events modules, and declaration):
```ruby
class Order
include AggregateRoot
include Orders::Events
def initialize
@status = :draft
end
attr_accessor :status
private
on OrderCreated do |_event|
@status = :created
end
def apply_order_expired(_event)
@status = :expired
end
end
```
usage of proposed declarative `on ` will be optional and will coexist with standard convention (after all its generating exactly same method like required by standard convention)
I see few pros of declarative …
=> support for declarative event handlers methods for aggregate root

rails_event_store-rspec/rails_event_store-rspec.gemspec
Without rspec gem tests are failing with LoadError:
cannot load such file -- rspec
Regression fix #115
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/railseventstore/rails_event_store/203)
=> Revert rspec as runtime dependency

ruby_event_store/lib/ruby_event_store/mappers/default.rb, ruby_event_store/lib/ruby_event_store/mappers/protobuf.rb, ruby_event_store/ruby_event_store.gemspec
Removing ActiveSupport dependency to avoid monkey patching and all the other fun stuff when not using Rails/ActiveRecord with RES
=> Remove ActiveSupport dependency from `ruby_event_store` gem

aggregate_root/aggregate_root.gemspec, bounded_context/bounded_context.gemspec, rails_event_store-browser/elm/src/Main.elm, rails_event_store-browser/rails_event_store-browser.gemspec, rails_event_store-rspec/rails_event_store-rspec.gemspec, rails_event_store/rails_event_store.gemspec, rails_event_store_active_record/rails_event_store_active_record.gemspec, railseventstore.org/README.md, railseventstore.org/source/docs/browser.html.md, ruby_event_store/ruby_event_store.gemspec
Change alll gems home page to https://railseventstore.org
Add metadata based on
https://olivierlacan.com/posts/changelogs-on-rubygems-org to have
changelog, source code & issue tracker links in RubyGems.org
=> Gems metadata update

rails_event_store_active_record/lib/rails_event_store_active_record/event_repository_reader.rb, rails_event_store_active_record/spec/event_repository_spec.rb
When reading via dedicated reader for traversing all streams we sort
event records by "id" only.
For traversing particular stream we primarily sort by "position", in
addition to "id".
We allow explicitly passing "all" stream to traverse this particular
stream and this is where discrepancy in resulting order appears.
Not sure if RDBMS beyond sqlite are affected.
=> Unstable order of read events from GLOBAL_STREAM.

rails_event_store_active_record/spec/event_repository_spec.rb, rails_event_store_active_record/spec/legacy_event_repository_spec.rb, ruby_event_store/lib/ruby_event_store/in_memory_repository.rb, ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb, ruby_event_store/spec/in_memory_repository_spec.rb
We allow reading from "all" stream like it is any other stream. Due to
implementation detail InMemoryRepository does not allow that.
=> Allow explicit read from GLOBAL_STREAM in InMemoryRepository

rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb, rails_event_store_active_record/lib/rails_event_store_active_record/legacy_event_repository.rb, rails_event_store_active_record/spec/event_repository_spec.rb, rails_event_store_active_record/spec/legacy_event_repository_spec.rb, rails_event_store_active_record/spec/v1_v2_schema_migration_spec.rb, ruby_event_store/lib/ruby_event_store/in_memory_repository.rb, ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb, ruby_event_store_rom_sql/lib/ruby_event_store/rom/event_repository.rb, ruby_event_store_rom_sql/spec/rom/event_repository_spec.rb
=> Fluent API, part two.

aggregate_root/aggregate_root.gemspec, aggregate_root/lib/aggregate_root.rb, aggregate_root/lib/aggregate_root/default_apply_strategy.rb, aggregate_root/spec/aggregate_root_spec.rb, aggregate_root/spec/spec_helper.rb
`to_snake_case` is almost copied from Rails
[underscore](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-underscore)
implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/railseventstore/rails_event_store/288)
=> Remove ActiveSupport dependency

rails_event_store-rspec/lib/rails_event_store/rspec/be_event.rb, rails_event_store-rspec/lib/rails_event_store/rspec/have_applied.rb, rails_event_store-rspec/lib/rails_event_store/rspec/have_published.rb, rails_event_store-rspec/lib/rails_event_store/rspec/matchers.rb, rails_event_store-rspec/spec/rails_event_store/rspec/be_event_spec.rb, rails_event_store-rspec/spec/rails_event_store/rspec/have_applied_spec.rb, rails_event_store-rspec/spec/rails_event_store/rspec/have_published_spec.rb, rails_event_store-rspec/spec/rails_event_store/rspec/matchers_spec.rb
This pull request improves verbosity of RES matchers descriptions in rspec --format doc
Matcher like
```
expect(FooEvent.new(data: { foo: "bar" }, metadata: { timestamp: Time.now }))
.to(matcher(FooEvent).with_data(foo: "bar")
.and(matcher(FooEvent).with_metadata(timestamp: kind_of(Time))))
```
Will be much more verbose now:
```
should be an event FooEvent (with data including {:foo=>"bar"}) and be an event FooEvent (with metadata including {:timestamp=>kind of Time})
```
=> Add more verbose descriptions

ruby_event_store/lib/ruby_event_store/event.rb, ruby_event_store/spec/event_spec.rb, ruby_event_store/spec/mappers/protobuf_spec.rb, ruby_event_store/spec/spec_helper.rb, ruby_event_store/spec/support/correlatable.rb
https://blog.arkency.com/correlation-id-and-causation-id-in-evented-systems/
> Let’s say every message has 3 ids. 1 is its id. Another is correlation the last
> it causation. If you are responding to a message, you copy its correlation id
> as your correlation id, its message id is your causation id. This allows you to
> see an entire conversation (correlation id) or to see what causes what (causation id).
Issue: #346
=> Event#correlate_with

aggregate_root/Makefile, aggregate_root/lib/aggregate_root.rb, aggregate_root/spec/aggregate_root_spec.rb
To prevent killing someones app by performing massive query via repository. 
We decided to ignore it since it's very hard to satisfy mutant within current `AggregateRoot` design. To kill the mutation we would need to be sure that *Repository performs certain operation. See df502227d5d5dae26ad0e88420a99473fc5d8206 for reference.
=> AggregatRoot loads events in batches

rails_event_store/lib/rails_event_store/active_job_dispatcher.rb, rails_event_store/lib/rails_event_store/all.rb, rails_event_store/lib/rails_event_store/async_dispatcher.rb, rails_event_store/spec/async_dispatcher_spec.rb
Breaking change: signature of dispatcher's proxy strategy is changed
=> Allow to use any background job library to handle async jobs

rails_event_store-rspec/Makefile, rails_event_store-rspec/lib/rails_event_store/rspec.rb, rails_event_store-rspec/lib/rails_event_store/rspec/matchers.rb, rails_event_store-rspec/lib/rails_event_store/rspec/publish.rb, rails_event_store-rspec/spec/rails_event_store/rspec/matchers_spec.rb, rails_event_store-rspec/spec/rails_event_store/rspec/publish_spec.rb
Allow to wrap a block with publish matcher to verify if block have published
a given event. Works also with passing a block that yields all events published
within a block, e.g.
```
expect {
event_store.publish_event(FooEvent.new)
}.to publish.in(event_store) do |events|
expect(events).to include(an_event(FooEvent))
}
```
or
```
expect {
MyService.new.call
}.to publish(an_event(FooEvent)).in_stream("Foo$1234").in(event_store)
```
=> Publish rspec matcher

rails_event_store/lib/rails_event_store/link_by_metadata.rb
The way super handles arguments is as follows: When you invoke super with no arguments Ruby sends a message to the parent of the current object, asking it to invoke a method of the same name as the method invoking super. It automatically forwards the arguments that were passed to the method from which it's called.
=> Kills some mutants

rails_event_store-rspec/lib/rails_event_store/rspec/publish.rb, rails_event_store-rspec/spec/rails_event_store/rspec/publish_spec.rb, rails_event_store_active_record-legacy/lib/rails_event_store_active_record/legacy/event_repository.rb, rails_event_store_active_record/lib/rails_event_store_active_record/event_repository_reader.rb, ruby_event_store-rom/lib/ruby_event_store/rom/event_repository.rb, ruby_event_store-rom/lib/ruby_event_store/rom/repositories/events.rb, ruby_event_store/lib/ruby_event_store/in_memory_repository.rb, ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb, ruby_event_store/lib/ruby_event_store/specification.rb, ruby_event_store/spec/specification_spec.rb
Now it will be possible:
```
first_event_in_dummy_stream = event_store.read.stream("Dummy").first
last_event_published = event_store.read.last
```
=> Add first/last to read specification

ruby_event_store/lib/ruby_event_store/client.rb, ruby_event_store/spec/client_spec.rb
=> Make RubyEventStore methods return self instead of ok

rails_event_store_active_record-legacy/lib/rails_event_store_active_record/legacy/event_repository.rb, rails_event_store_active_record-legacy/spec/legacy_event_repository_spec.rb, rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb, ruby_event_store-rom/lib/ruby_event_store/rom/adapters/memory/relations/stream_entries.rb, ruby_event_store-rom/lib/ruby_event_store/rom/adapters/sql/relations/stream_entries.rb, ruby_event_store-rom/lib/ruby_event_store/rom/event_repository.rb, ruby_event_store-rom/lib/ruby_event_store/rom/repositories/stream_entries.rb, ruby_event_store/lib/ruby_event_store/in_memory_repository.rb, ruby_event_store/lib/ruby_event_store/instrumented_repository.rb, ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb, ruby_event_store/spec/instrumented_repository_spec.rb
Finds all streams for given event id, excluding global stream.
=> Streams of event

aggregate_root/Makefile, aggregate_root/spec/support/mutant_timeout.rb, bounded_context/Makefile, bounded_context/spec/support/mutant_timeout.rb, rails_event_store-browser/Makefile, rails_event_store-browser/spec/support/mutant_timeout.rb, rails_event_store-rspec/Makefile, rails_event_store-rspec/spec/support/mutant_timeout.rb, rails_event_store/Makefile, rails_event_store/spec/support/mutant_timeout.rb, rails_event_store_active_record-legacy/Makefile, rails_event_store_active_record-legacy/spec/support/mutant_timeout.rb, rails_event_store_active_record/Makefile, rails_event_store_active_record/spec/support/mutant_timeout.rb, ruby_event_store-browser/Makefile, ruby_event_store-browser/spec/support/mutant_timeout.rb, ruby_event_store-rom/Makefile, ruby_event_store-rom/spec/support/mutant_timeout.rb, ruby_event_store/spec/support/mutant_timeout.rb
* We have these timeouts only for the sake of mutant sometimes
going (intentionally) in infinite loop
* If you wanted to use the debugger, you had to comment these timeouts
* After debugging you had to remember to uncomment the timeouts
This commit solves these problems
=> Timeout only if mutating

ruby_event_store-browser/lib/ruby_event_store/browser/app.rb, ruby_event_store-browser/ruby_event_store-browser.gemspec
This was tested with Sinatra 1.4.8 and 2.x. Not putting a version constraint ought to allow for mounting in any version of Rails.
@pawelpacana does this address (or mitigate) the issue you had?
=> Make Sinatra 1.4.8 and 2.x compatible by fixing route pattern

ruby_event_store/lib/ruby_event_store/event.rb, ruby_event_store/lib/ruby_event_store/mappers/protobuf.rb, ruby_event_store/spec/event_spec.rb
This allows putting anything as data, eg. nil, Array, Struct, etc.
However, we added {} as a default value for the data to prevent breaking
applications relying on data being hash and using methods like [] or
fetch.
[#395]
=> to_h is no longer callled on event data

railseventstore.org/source/docs/exceptions.html.md, ruby_event_store/lib/ruby_event_store/errors.rb, ruby_event_store/lib/ruby_event_store/mappers/protobuf.rb, ruby_event_store/spec/mappers/protobuf_spec.rb
This allows dropping custom initializer for RubyEventStore::Proto
[#409]
=> Verify Protobuf event data presence in mapper

ruby_event_store/lib/ruby_event_store/mappers/default.rb, ruby_event_store/spec/mappers/default_spec.rb
- it is required now for metadata keys to be symbols
- some serializers (JSON) dump to strings and have no way to figure out
we want symbols back
- metadata has a flat structure at the time being so no deep symbolize
is needed
Related:
https://github.com/RailsEventStore/rails_event_store/issues/367#issuecomment-396488606
Data keys being converted to strings left intact. Handling symbol/string
duality would be better suited in your event wrapper:
```ruby
class MyEvent < RubyEventStore::Event
def data
HashWithIndiffetentAccessOrSomethingElse.new(data)
end
end
```
=> Symbolize metadata keys by default

rails_event_store-rspec/Gemfile, rails_event_store/Gemfile, rails_event_store/lib/rails_event_store/all.rb, rails_event_store/lib/rails_event_store/browser.rb, rails_event_store/rails_event_store.gemspec, rails_event_store/spec/browser_integration_spec.rb, rails_event_store/spec/middleware_integration_spec.rb, rails_event_store/spec/spec_helper.rb, rails_event_store/spec/support/test_application.rb, ruby_event_store-browser/spec/defaults_spec.rb
Except it is really tiny this time:
- provide event_store location OOTB
- depend on browser, like all-batteries included RailsEventStore should
[#483]
=> Resurrect RailsEventStore::Browser.

aggregate_root/spec/aggregate_root_spec.rb, rails_event_store-rspec/lib/rails_event_store/rspec/publish.rb, rails_event_store/spec/client_spec.rb, rails_event_store/spec/full_story_spec.rb, rails_event_store/spec/link_by_metadata_spec.rb, rails_event_store/spec/protobuf_integration_spec.rb, railseventstore.org/source/docs/exceptions.html.md, railseventstore.org/source/docs/link.html.md, railseventstore.org/source/docs/protobuf.html.md, railseventstore.org/source/docs/publish.html.md, railseventstore.org/source/docs/read.html.md, railseventstore.org/source/docs/request_metadata.html.md, ruby_event_store-browser/lib/ruby_event_store/browser/stream.rb, ruby_event_store/lib/ruby_event_store/batch_enumerator.rb, ruby_event_store/lib/ruby_event_store/client.rb, ruby_event_store/lib/ruby_event_store/deprecated_read_api_rewriter.rb, ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb, ruby_event_store/lib/ruby_event_store/specification.rb, ruby_event_store/spec/batch_enumerator_spec.rb, ruby_event_store/spec/client_spec.rb, ruby_event_store/spec/client_subscriptions_spec.rb, ruby_event_store/spec/deprecated_spec_api_rewriter_spec.rb, ruby_event_store/spec/link_by_metadata_spec.rb, ruby_event_store/spec/specification_spec.rb
=> Implementation of to_a

railseventstore.org/source/docs/repository.html.md
Hi there 👋)
"ex**ep**cted_version option" -> "ex**pe**cted_version option"
=> Repository docs typo

ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb
https://mutation-testing.slack.com/archives/C0A0RSER3/p1548119255010800
=> Exclude concurrency-related tests from mutant selection.

aggregate_root/lib/aggregate_root.rb, aggregate_root/lib/aggregate_root/repository.rb, aggregate_root/spec/aggregate_root_spec.rb
It have been killed long time ago https://github.com/RailsEventStore/rails_event_store/commit/54b93a72372314c4a6dbdecf8b3cfc8aa645f577#diff-1d5e211055c3d9a6b2b9e4314668a3dc
Now it is going back. The promisses from `Redesign of aggregate root
module` commit still holds true:
* still no magic
* still no restrictions on how aggregate class should look like, etc
This is a breaking change. Instead of:
```
order = Order.new.load("OrderStreamHere")
...
order.store
```
you need to have code:
```
repository = AggregateRoot::Repository.new
order = repository.load(Order.new, "OrderStreamHere")
...
repository.store(order, "OrderStreamHere")
```
=> Restore AggregateRoot::Repository

ruby_event_store/Gemfile
No need for custom-built on private gem server. That would work for the rest of the year until new Ruby release...
=> Yay, stock protobuf gems.

railseventstore.org/source/index.html.md
Currently, we have this title for the root page :
=> Add title for the root page

rails_event_store-rspec/lib/rails_event_store/rspec/have_applied.rb, rails_event_store-rspec/spec/rails_event_store/rspec/have_published_spec.rb, rails_event_store-rspec/spec/rails_event_store/rspec/publish_spec.rb, ruby_event_store/lib/ruby_event_store/mappers/null_mapper.rb, ruby_event_store/lib/ruby_event_store/serialized_record.rb, ruby_event_store/lib/ruby_event_store/spec/mapper_lint.rb, ruby_event_store/spec/mappers/default_spec.rb, ruby_event_store/spec/mappers/encryption_mapper_spec.rb, ruby_event_store/spec/mappers/null_mapper_spec.rb, ruby_event_store/spec/mappers/protobuf_spec.rb, ruby_event_store/spec/serialized_record_spec.rb, support/helpers/protobuf_helper.rb
=> NullMapper in form of Default + null serializer

railseventstore.org/source/docs/migrating_messages.html.md
I think that the "Change event type" section would not work since it's overwriting with the same array as before. We would need to store the map in a variable, if I am not mistaken.
=> Possible fix for in Migrating_Messages.html.md

contrib/measure/Gemfile, contrib/measure/examples/demo, contrib/measure/lib/measure.rb, contrib/measure/lib/measure/version.rb, contrib/measure/measure.gemspec, contrib/measure/spec/measure_spec.rb, contrib/measure/spec/spec_helper.rb
Given a block of instrumented RES code, print aggregated time of each RES
metric with percentage of total block execution time.
Example:
```
metric                  ms      %
─────────────────────────────────
read                  0.02   0.13
serialize            10.68  66.22
append_to_stream      0.87   5.41
total                16.13 100.00
```
Right now, it expects (hardcoded) `ActiveSupport::Notifications` but it
doesn't have to be this way.
Testing unfortunately relies on magic number of mocked Time.now
execution. Something that may unexpectedly change in the future.
=> Simple benchmark from RES instrumentation

aggregate_root/lib/aggregate_root.rb, aggregate_root/spec/aggregate_root_spec.rb
This allows an aggregate to have its initializer while still being able
to set our ivars when object is constructed.
https://ruby-doc.org/core-2.2.0/Class.html#method-i-new
=> Have a constructor while still allowing redefining initialize.

ruby_event_store-rom/lib/ruby_event_store/rom.rb, ruby_event_store-rom/lib/ruby_event_store/rom/adapters/memory/relations/stream_entries.rb, ruby_event_store-rom/lib/ruby_event_store/rom/adapters/memory/unit_of_work.rb, ruby_event_store-rom/lib/ruby_event_store/rom/adapters/sql/changesets/update_events.rb, ruby_event_store-rom/lib/ruby_event_store/rom/adapters/sql/tasks/migration_tasks.rake, ruby_event_store-rom/lib/ruby_event_store/rom/event_repository.rb, ruby_event_store-rom/lib/ruby_event_store/rom/memory.rb, ruby_event_store-rom/lib/ruby_event_store/rom/sql.rb, ruby_event_store-rom/lib/ruby_event_store/rom/types.rb, ruby_event_store-rom/lib/ruby_event_store/rom/unit_of_work.rb, ruby_event_store-rom/lib/ruby_event_store/rom/version.rb, ruby_event_store-rom/lib/ruby_event_store/spec/rom/event_repository_lint.rb, ruby_event_store-rom/lib/ruby_event_store/spec/rom/relations/events_lint.rb, ruby_event_store-rom/lib/ruby_event_store/spec/rom/relations/stream_entries_lint.rb, ruby_event_store-rom/lib/ruby_event_store/spec/rom/spec_helper_lint.rb, ruby_event_store-rom/lib/ruby_event_store/spec/rom/unit_of_work_lint.rb, ruby_event_store-rom/ruby_event_store-rom.gemspec, ruby_event_store-rom/spec/rom/adapters/memory/relations/events_spec.rb, ruby_event_store-rom/spec/rom/adapters/memory/relations/stream_entries_spec.rb, ruby_event_store-rom/spec/rom/env_spec.rb, ruby_event_store-rom/spec/spec_helper.rb
This upgrade of dry-types introduces breaking changes for any dry-* dependencies projects may have.
There are no breaking changes in RES, only minor updates to internals.
@paneq @pawelpacana I'll let you guys merge this. Not sure if you have any concerns or opinions about this upgrade -- it should only affect projects using the ROM adapter who also depend on DRY gems.
=> Upgrade ROM adapter dependencies (dry-types v1.0, rom v5.0, rom-sql v3.0)

aggregate_root/lib/aggregate_root.rb, aggregate_root/lib/aggregate_root/default_apply_strategy.rb, aggregate_root/spec/aggregate_root_spec.rb, aggregate_root/spec/spec_helper.rb
The problem with the removal of the ancestor chain of `on_methods` is that the default strategy gets a copy of `@on_methods` from the base class that the `AggregateRoot` module is included in. When a class inherits from that base class, any additional events handled in the sublcass are not added to the `@on_methods` hash already captured by the default strategy.
The proposed solution accesses `on_methods` directly on the aggregate inside the default strategy, and restores merging `@on_methods` through the ancestor chain.
Addresses one of the issues mentioned in #596
=> AggregateRoot `on_methods` inheritance

aggregate_root/Gemfile, aggregate_root/lib/aggregate_root.rb, aggregate_root/lib/aggregate_root/instrumented_repository.rb, aggregate_root/spec/instrumented_repostory_spec.rb, aggregate_root/spec/spec_helper.rb
Instruments `load` & `store` methods. Tracks aggregate class, stream and
for storing also current aggregate version & number of events stored.
=> AggregateRoot's repository instrumentation

railseventstore.org/source/docs/app.html.md.erb
This PR just adds a few missing definite or indefinite articles to the explanations provided in the documentation, corrects several spelling mistakes to yield a more readable sentence structure. No changes to the code examples.
=> Improve documentation readability

railseventstore.org/source/docs/read.html.md.erb
Adds definite and indefinite articles where appropriate, and fixes tense to improve consistency and overall readability of the documentation. No changes to the code examples.
=> Improve documentation readability in `Reading events`

ruby_event_store-browser/devserver/config.ru, ruby_event_store-browser/elm/elm.json, ruby_event_store-browser/elm/src/Api.elm, ruby_event_store-browser/elm/src/Main.elm, ruby_event_store-browser/elm/src/Page/ShowEvent.elm, ruby_event_store-browser/elm/src/Page/ViewStream.elm, ruby_event_store-browser/elm/src/TimeHelpers.elm, ruby_event_store-browser/elm/src/style/base/_tables.scss, ruby_event_store-browser/elm/src/style/components/_event.scss, ruby_event_store-browser/elm/tests/DecodersTest.elm
- When "Caused events" list is long, display information that it may be truncated.
- Remove underline from stream links, as streams often have `_` in names and it is less readable with underlines.
- Format timestamps nicer, instead of raw iso8601 display something like `10.06.2019, 15:20:57.602`
- Display more relevant html title: Either stream or event you are at, so the flow is nicer when you already have few tabs with browser opened :)
=> Browser UI improvements

ruby_event_store-browser/elm/src/Api.elm, ruby_event_store-browser/elm/src/Page/ShowEvent.elm, ruby_event_store-browser/elm/src/style/components/_event.scss, ruby_event_store-browser/elm/tests/DecodersTest.elm, ruby_event_store-browser/lib/ruby_event_store/browser/event.rb, ruby_event_store-browser/lib/ruby_event_store/browser/json_api_event.rb, ruby_event_store-browser/lib/ruby_event_store/browser/stream.rb, ruby_event_store-browser/spec/api_spec.rb
=> Link to parent event in Browser

rails_event_store/lib/rails_event_store/after_commit_async_dispatcher.rb, rails_event_store/spec/after_commit_async_dispatcher_spec.rb
I was using the `AfterCommitAsyncDispatcher` along with Sidekiq workers and I couldn't get integration tests working (with inlined Sidekiq workers and Database Cleaner's transaction strategy).
This solution follows a similar pattern from change to Rails https://github.com/rails/rails/pull/18458
=> Ensure AfterCommitAsyncDispatcher runs handlers in tests

ruby_event_store-browser/elm/src/Page/ViewStream.elm, ruby_event_store-browser/elm/src/Route.elm, ruby_event_store-browser/elm/src/style/components/_pagination.scss
Little changes to pagination buttons.
Previously only the active buttons were shown, which meant that after few times you've clicked "next" (and got to the last page), you had "previous" button in the same place, which was pretty frustrating experience. Now, the inactive buttons are just disabled. Also, the order of buttons has changed, from `first / last / next / previous` to more commonly used `first / previous / next / last`.
=> Pagination buttons

ruby_event_store-browser/lib/ruby_event_store/browser/app.rb
As of Sinatra 2.0.6, `Sinatra::Application` parses ARGV when the classes are loaded, even if only using `Sinatra::Application` as middleware or not using it at all. Since we switched to using `Sinatra::Base` already, this more specific require should fix things up.
=> Only require Sinatra::Base

railseventstore.org/source/docs/request_metadata.html.md
Putting an `end` to on a super minor issue in the docs 😄. Setting request metadata example was missing `end`.
=> Add missing end in the docs

ruby_event_store/lib/ruby_event_store/projection.rb, ruby_event_store/spec/projection_spec.rb
=> Make use of of_type in projections to skip irrelevant events

rails_event_store-rspec/lib/rails_event_store/rspec.rb, rails_event_store-rspec/lib/rails_event_store/rspec/apply.rb, rails_event_store-rspec/lib/rails_event_store/rspec/matchers.rb, rails_event_store-rspec/lib/rails_event_store/rspec/publish.rb, rails_event_store-rspec/spec/rails_event_store/rspec/apply_spec.rb, rails_event_store-rspec/spec/rails_event_store/rspec/matchers_spec.rb
Instead of checking what have_applied by aggregate action this matcher
will check what have applied during the action.
This will allow to write test like:
```
aggtegate = SomeAggregate.new
aggregate.do_something
expect { aggregate.do_anything_else }.to
apply(an_event(SomeEvent)).in(aggregate)
```
The advantage is that we will be able what exactly have been
applied during the aggregate logic execution.
=> Apply matcher for testing AggregateRoot

ruby_event_store/lib/ruby_event_store/event.rb, ruby_event_store/spec/event_spec.rb
* not used anywhere within RailsEventStore
* if you need to_h for your events, you should create
a wrapper or your own Event class - see example here:
https://github.com/RailsEventStore/cqrs-es-sample-with-res/blob/master/lib/event.rb
=> Minimize API: remove to_h from RubyEventStore::Event

ruby_event_store/lib/ruby_event_store/spec/event_lint.rb
Some Event class implementation could use different models
for data & metadata attribute. Some of them might have requirements
that could not be fulfilled by Object instance. By default Event linter
will use new object instance for as adata object and empty hash as
metadata (to match all requirements for metadata) but will allow
to pass exact instances to be used while checking event's class
implementation.
=> Allow to pass data and metadata instances to event linter

rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb
This will lower number of SQL calls from N+2
to 3 (in best case) (where N is number of events).
=> Use Event.import instead of making N save calls

rails_event_store_active_record/lib/rails_event_store_active_record.rb, rails_event_store_active_record/lib/rails_event_store_active_record/batch_enumerator.rb, rails_event_store_active_record/lib/rails_event_store_active_record/event_repository_reader.rb, rails_event_store_active_record/spec/batch_enumerator_spec.rb, rails_event_store_active_record/spec/event_repository_spec.rb
Hi @mpraglowski 
I've closed #746 as it was really messed up with commits, merges and rebases. Here is clean commits history.
=> Value based offset

rails_event_store_active_record/Makefile, rails_event_store_active_record/lib/rails_event_store_active_record/event.rb, rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb, rails_event_store_active_record/lib/rails_event_store_active_record/event_repository_reader.rb, rails_event_store_active_record/lib/rails_event_store_active_record/generators/created_at_precision_generator.rb, rails_event_store_active_record/lib/rails_event_store_active_record/generators/no_global_stream_entries_generator.rb, rails_event_store_active_record/lib/rails_event_store_active_record/generators/templates/create_event_store_events_template.rb, rails_event_store_active_record/lib/rails_event_store_active_record/generators/templates/created_at_precision_template.rb, rails_event_store_active_record/lib/rails_event_store_active_record/generators/templates/no_global_stream_entries_template.rb, rails_event_store_active_record/lib/rails_event_store_active_record/index_violation_detector.rb, rails_event_store_active_record/spec/event_repository_spec.rb, rails_event_store_active_record/spec/migrations_spec.rb, ruby_event_store/spec/specification_spec.rb, support/bundler/Gemfile.1_0_0, support/bundler/Gemfile.1_1_1, support/helpers/schema_helper.rb
What this means is that we get one INSERT statement less for non-named stream appends and we store half of the entries in event_store_events (if all your event publishes are in named-streams). 
Reduced storage size and theoretical write-side improvement in one case.
=> No global stream entries in event_store_events_in_streams

rails_event_store/lib/rails_event_store/async_handler_helpers.rb, rails_event_store/spec/async_handler_helpers_spec.rb, ruby_event_store-browser/spec/api_spec.rb, ruby_event_store/lib/ruby_event_store/client.rb, ruby_event_store/spec/client_notify_subscribers_spec.rb, ruby_event_store/spec/client_spec.rb
Was:
```
event A              -> event B            -> event C
corrleation_id: nil     correlation_id: A     correlation_id: A
causation_id: nil       causation_id: A       causation_id: B
```
Is now:
```
event A              -> event B            -> event C
correlation_id: X     correlation_id: X     correlation_id: X
causation_id: nil     causation_id: A       causation_id: B
```
=> Correlation ID, course correction

.circleci/config.rb, .circleci/config.yml
First release of Rails 4.x was in 2014. It will still likely be
supported.
It makes things simpler from development perspective and we'll
about to see Rails 6.1 soon, so it will become no longer supported in security
patches as well.
=> Drop testing on Rails 4.2

support/bundler/Gemfile.shared
* This release changes to consider mutations that make rspec crash as
covered as long `process_abort: true` is active as a coverage criteria.
=> Bump to mutant 0.10.14

aggregate_root/Gemfile, aggregate_root/Gemfile.lock, bounded_context/Gemfile, bounded_context/Gemfile.rails_5_0, bounded_context/Gemfile.rails_5_1, bounded_context/Gemfile.rails_5_2, rails_event_store-rspec/Gemfile, rails_event_store-rspec/Gemfile.rails_5_0, rails_event_store-rspec/Gemfile.rails_5_1, rails_event_store-rspec/Gemfile.rails_5_2, rails_event_store/Gemfile, rails_event_store/Gemfile.lock, rails_event_store/Gemfile.rails_5_0, rails_event_store/Gemfile.rails_5_1, rails_event_store/Gemfile.rails_5_2, rails_event_store_active_record/Gemfile, rails_event_store_active_record/Gemfile.rails_5_0, rails_event_store_active_record/Gemfile.rails_5_1, rails_event_store_active_record/Gemfile.rails_5_2, ruby_event_store-browser/Gemfile, ruby_event_store-rom/Gemfile, ruby_event_store/Gemfile, support/bundler/Gemfile.shared
I'd very much like to use dependabot to bump dev dependencies,
especially with regard to rails and mutant versions used.
=> Evaled Gemfile does not work with dependabot

ruby_event_store/lib/ruby_event_store/client.rb, ruby_event_store/lib/ruby_event_store/spec/subscriptions_lint.rb, ruby_event_store/lib/ruby_event_store/subscriptions.rb, ruby_event_store/spec/client_spec.rb
Make implicit explicit. Type resolver is reponsible
for converting event type from anything (class, string, etc)
to event type (string preffered here).
Default implementation (backward compatible) is just
lambda using to_s method to convert event type
given as class or string to string.
=> Allow to specify event type resolver for subscriptions

rails_event_store_active_record/lib/rails_event_store_active_record/event_repository.rb, rails_event_store_active_record/spec/event_repository_spec.rb
It has been used bt DRES, but seems to be not there anymore
=> Drop unused fill_ids method

ruby_event_store-rspec/lib/ruby_event_store/rspec.rb, ruby_event_store-rspec/lib/ruby_event_store/rspec/crude_failure_message_formatter.rb, ruby_event_store-rspec/lib/ruby_event_store/rspec/have_published.rb, ruby_event_store-rspec/lib/ruby_event_store/rspec/step_by_step_failure_message_formatter.rb, ruby_event_store-rspec/spec/ruby_event_store/rspec/have_published_spec.rb
setting configuration on RSpec is better than setting it on the class which is not part of the public API (RSpec::HavePublished)
=> Move setting formatter to RSpec module

railseventstore.org/source/docs/v2/delete.html.md
I wanted to remove all events and event streams from my test app, so I tried the delete_method. I was confused why it did not delete the events themselves, only the streams. Then I found the note on the source code.
=> docs(delete): add note for immutability of events

ruby_event_store-browser/elm/src/index.js, ruby_event_store-browser/lib/ruby_event_store/browser/app.rb, ruby_event_store-browser/spec/defaults_spec.rb, ruby_event_store-browser/spec/ui_spec.rb
I finally got around to working on a fix for the problem I've described in #1062 and here's what I've come up with.
First of all I added a test to ui tests that serves the browser together with a reasonable CSP header. What's important is that this header does not include a `script-src 'unsafe-inline'` which would be the only way to make the inline script initiating the `Browser` work with CSP. So this test failed before I've implemented the changes.
And the rest is what we've discussed in the issue: I've moved the settings from the inline JS to a `meta` tag and dumped them as JSON. Then the JSON is retrieved in `index.js` and used to initiate the `Browser` there.
I've also removed the code exposing the `Browser` via `window.RubyEventStore.Browser` as @pawelpacana suggested in #1062.
=> Browser compatibility with Content Security Policy

railseventstore.org/.babelrc, railseventstore.org/package-lock.json, railseventstore.org/package.json, railseventstore.org/source/layouts/base.erb, railseventstore.org/vite.config.js, ruby_event_store-browser/Makefile, ruby_event_store-browser/elm/package-lock.json, ruby_event_store-browser/elm/package.json, ruby_event_store-browser/elm/src/index.js, ruby_event_store-browser/elm/src/style/style.css, ruby_event_store-browser/elm/vite.config.js
Reasons:
* dropping babel transpiling and dependency (it's 2021, ES is so 2015)
* parcel 1 did not support postcss 8 and that blocked whole chain of
css-related dependencies
* up-to-date build tool with less or modern dependencies is means less
frequent dependabot PRs and npm audit warnings
* seems to work equally good and not grabbing attention, continuing the
spirit of Parcel
=> Migrate from Parcel to Vite

rails_event_store/lib/rails_event_store/async_handler_helpers.rb, rails_event_store/spec/async_handler_helpers_spec.rb
Because eager loading of the event store is not suitable to
legacy applications. Howevery current event_store: option will be
removed only at RES 3.0.
=> Add event_store_locator option to AsyncHandler

contrib/ruby_event_store-sidekiq_scheduler/lib/ruby_event_store/sidekiq_scheduler.rb
Sidekiq 6.4 has started to log warnings
(https://github.com/mperham/sidekiq/pull/5071) if the job arguments are
not strictly JSON-safe i.e. serializing to JSON and deserializing from
JSON yield consistent outputs. To what it means, we cannot use a hash
with symbol keys since doing the JSON rountrip will change them all to
string keys.
This fix will transform the hash argument with symbol keys to string
keys so Sidekiq won't complain it (and break it starting version 7.0).
=> chore: resolve sidekiq json-unsafe warning

contrib/ruby_event_store-rom/lib/ruby_event_store/rom.rb, contrib/ruby_event_store-rom/lib/ruby_event_store/rom/tasks/migration_tasks.rake, railseventstore.org/source/docs/v2/without_rails.html.md
Currently initialization for ROM does not work because of number of things:
* `::RubyEventStore::ROM.configure` having been removed - I replaced it with a call to `::RubyEventStore::ROM.rom_container`, which I made public, but maybe a public proxy `.configure` would be better
* Wrong source migration path
* `ROM::SQL::RakeSupport.create_migration` trying to create output migration in a really weird path (in Ruby 3): 
```
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - db/migrate/{:path=>"/Users/katafrakt/dev/palaver/db/migrate"}_create_ruby_event_store_tables.rb
/Users/katafrakt/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rom-sql-3.5.0/lib/rom/sql/migration/migrator.rb:54:in `write'
```
* Non-existing require path in instructions
This PR fixes all four, making …
=> Fix initialization for ROM

contrib/ruby_event_store-outbox/lib/ruby_event_store/outbox/cleanup_strategies/clean_old_enqueued.rb, contrib/ruby_event_store-outbox/lib/ruby_event_store/outbox/cli.rb, contrib/ruby_event_store-outbox/lib/ruby_event_store/outbox/consumer.rb, contrib/ruby_event_store-outbox/lib/ruby_event_store/outbox/repository.rb, contrib/ruby_event_store-outbox/spec/consumer_spec.rb, contrib/ruby_event_store-outbox/spec/sidekiq_correctness_spec.rb
Sometimes cleanup of old entries could be time consuming because of numbers of records already stored in database. The limit (if set) will allow to make sure cleanup operation will finish in reasonable amount of time, leaving records over the limit for the next cleanup run.
=> Cleanup only up to limit

contrib/distributed_rails_event_store/dres_rails/Gemfile.lock, contrib/ruby_event_store-protobuf/Gemfile.lock, contrib/ruby_event_store-protobuf/Gemfile.rails_6_0.lock, contrib/ruby_event_store-protobuf/Gemfile.rails_6_1.lock, rails_event_store/Gemfile.lock, rails_event_store/Gemfile.rails_6_0.lock, rails_event_store/Gemfile.rails_6_1.lock, rails_event_store/spec/dummy_6_0/Gemfile.lock, rails_event_store/spec/dummy_6_1/Gemfile.lock, rails_event_store/spec/dummy_7_0/Gemfile.lock, ruby_event_store-browser/Gemfile.lock, ruby_event_store-browser/lib/ruby_event_store/browser/app.rb, ruby_event_store-browser/lib/ruby_event_store/browser/routing.rb, ruby_event_store-browser/ruby_event_store-browser.gemspec
https://github.com/RailsEventStore/rails_event_store/issues/958
* Rack::Static to serve compiled JS from public path
* Rack::Request for nice facade over Rack env
* lacking Rack::Protection, which can be re-added if neeeded
* case pattern matching seems simple and sufficient for such a tiny app that Browser is,
good thing that it uses === and that plays nicely with Regexp,
* one drawback is that it is also quite verbose without that fancy DSL for regex-matching
URL patterns behind the scenes
* a few rough edges like unnamed and a bit too wide (thus order dependent) regexes,
decoding params and endless string-vs-symbol whack-a-mole
Examples of router implementation:
https://github.com/pjb3/rack-router
https://github.com/mperham/sidekiq/commit/9ea167db16bf7f4cc9ee94967d0ea0b4dee6a7c5
=> Browser — drop sinatra dependency

contrib/ruby_event_store-outbox/lib/ruby_event_store/outbox.rb, contrib/ruby_event_store-outbox/lib/ruby_event_store/outbox/consumer.rb, contrib/ruby_event_store-outbox/lib/ruby_event_store/outbox/sidekiq_processor.rb, contrib/ruby_event_store-outbox/spec/sidekiq_correctness_spec.rb
I am well aware that the tests are crap for these, i.e. there are no unit tests covering specific sidekiq processor (mostly because there is only a sidekiq processor and it's hard to abstract). I plan to improve tests later. Currently the behaviour is similar, but accidental: the consumer get the error (like timeout error), logs it, and then process next batch, starting from the same point. That will improve "performance" though, meaning the data won't be unnecessarily fetched again (we don't expect it to change, ever, so it doesn't make sense).
=> Outbox: automatically retry once on connection errors

ruby_event_store/lib/ruby_event_store/client.rb, ruby_event_store/spec/client_spec.rb
Make it consistent with append & publish.
=> Assert nil when linking events

ruby_event_store/lib/ruby_event_store/client.rb, ruby_event_store/spec/client_spec.rb
- Revert "Assert nil when linking events"
- Revert "Extract assertion to separate method and call it asap"
- Revert "Raise ArgumentError when trying to publish nil as event"
=> Changing facade API behaviour reverted

rails_event_store/spec/migration_spec.rb, ruby_event_store-active_record/lib/ruby_event_store/active_record.rb, ruby_event_store-active_record/lib/ruby_event_store/active_record/generators/migration_generator.rb, ruby_event_store-active_record/lib/ruby_event_store/active_record/railtie.rb
- Failing test case for broken public API
- Resurrect old migration generator name to maintain stable public API
=> Bring back rails_event_store_active_record:migration

contrib/ruby_event_store-sidekiq_scheduler/Gemfile, contrib/ruby_event_store-sidekiq_scheduler/Gemfile.lock, contrib/ruby_event_store-sidekiq_scheduler/Gemfile.sidekiq_5, contrib/ruby_event_store-sidekiq_scheduler/Gemfile.sidekiq_5.lock, contrib/ruby_event_store-sidekiq_scheduler/Gemfile.sidekiq_6, contrib/ruby_event_store-sidekiq_scheduler/Gemfile.sidekiq_6.lock, contrib/ruby_event_store-sidekiq_scheduler/Makefile, contrib/ruby_event_store-sidekiq_scheduler/spec/after_commit_async_dispatcher_spec.rb, contrib/ruby_event_store-sidekiq_scheduler/spec/async_handler_helpers_spec.rb, rails_event_store/spec/after_commit_async_dispatcher_spec.rb, rails_event_store/spec/async_handler_helpers_spec.rb
mainly: 
* moved non-ActiveJobScheduler test cases of `async_handler_helpers_spec.rb` into contrib/sidekiq-scheduler (which results in dev dependency on `rails_event_store` and `rails`)
* duplicated `after_commit_async_dispatcher_spec.rb` test, with a change of scheduler to be SidekiqScheduler, in contrib/sidekiq-scheduler
Additional dependencies in sidekiq-scheduler are a tradeoff we have to make if we want to move the Non-ActiveJobScheduler tests out of `rails_event_store`. The good thing is that those still show usage and are closer to the gem that the user might be interested in.
=> Move non aj scheduler handler tests to sidekiq scheduler gem

ruby_event_store-active_record/lib/ruby_event_store/active_record/event_repository_reader.rb, ruby_event_store-active_record/spec/event_repository_spec.rb
Using bi-temporal event sourcing with `valid_at` the order of the stream when using `#as_of` was fixed with https://github.com/RailsEventStore/rails_event_store/pull/1518 
I encountered another bug when using `#as_of` in combination with time filtering e.g. `older_than(time)`
`event_store.read.stream('stream').as_of.older_than(time).backward.limit(1).first`
Expected: Get the **valid** event before a given point in time.
Actual: The last event _created_ before that time.
Why? The following methods in `event_repository_reader.rb` use only `created_at` for filtering by time:
`older_than(time)`
`older_than_or_equal(time)`
`newer_than(time)`
`newer_than_or_equal(time)`
This fix uses `COALESCE(valid_at, created_at)` when filtering by time using `#as_of`.
=> fix(activerecord): #as_of filter by time

ruby_event_store-active_record/lib/ruby_event_store/active_record/event_repository_reader.rb, ruby_event_store-active_record/spec/event_repository_spec.rb
fixes 
```
:in `block in reverse_sql_order': Order "COALESCE(event_store_events.valid_at, event_store_events.created_at) ASC" cannot be reversed automatically (ActiveRecord::IrreversibleOrderError)
```
=> Fix read as of last

contrib/ruby_event_store-rom/lib/ruby_event_store/rom/repositories/events.rb, contrib/ruby_event_store-sequel/lib/ruby_event_store/sequel/event_repository.rb, ruby_event_store-active_record/lib/ruby_event_store/active_record/event_repository_reader.rb, ruby_event_store/lib/ruby_event_store/in_memory_repository.rb, ruby_event_store/lib/ruby_event_store/spec/event_repository_lint.rb, ruby_event_store/lib/ruby_event_store/specification.rb, ruby_event_store/lib/ruby_event_store/specification_reader.rb, ruby_event_store/spec/client_spec.rb, ruby_event_store/spec/specification_spec.rb
- cover current behaviour with a test
- same behavior of adapters when reading from or to non-existent event
- improve mutant coverage
- Validate starting and ending specification events only on execution
=> same behavior of adapters when reading from or to non existent event 

contrib/ruby_event_store-rom/lib/ruby_event_store/rom/relations/events.rb, contrib/ruby_event_store-rom/lib/ruby_event_store/rom/relations/stream_entries.rb, contrib/ruby_event_store-rom/lib/ruby_event_store/rom/repositories/events.rb
- avoid multiple SQL joins to the same query
- fix sorting events in rom integration
=> make rom green again

ruby_event_store-active_record/lib/ruby_event_store/active_record/batch_enumerator.rb, ruby_event_store-active_record/spec/batch_enumerator_spec.rb, ruby_event_store-active_record/spec/event_repository_spec.rb, ruby_event_store/lib/ruby_event_store/batch_enumerator.rb, ruby_event_store/spec/batch_enumerator_spec.rb
no need to fetch next batch if the previous one is smaller than specified batch size
(related to #1708)
=> batch enumerator optimization

rails_event_store/lib/rails_event_store/after_commit_async_dispatcher.rb
dead code
originally needed:
https://github.com/RailsEventStore/rails_event_store/commit/3feb47d938907a289e90ce51e2fb5a0d541972d1
and since we require ActiveRecord >= 6 it is no longer needed:
https://github.com/rails/rails/commit/9030b7c7751ba8375697baaee461b1a6435ad5fe
=> possibly a dead code

ruby_event_store-active_record/spec/transactions_spec.rb
- Document current behaviour more thoroughly before altering it
- Make verbose logging optional with VERBOSE=true
- One more usage variation
=> transaction specs

aggregate_root/Gemfile.lock, aggregate_root/aggregate_root.gemspec, aggregate_root/lib/aggregate_root/snapshot_repository.rb, contrib/dres_rails/Gemfile.lock, contrib/minitest-ruby_event_store/Gemfile.lock, contrib/ruby_event_store-profiler/Gemfile.lock, contrib/ruby_event_store-protobuf/Gemfile.lock, contrib/ruby_event_store-protobuf/Gemfile.rails_6_0.lock, contrib/ruby_event_store-protobuf/Gemfile.rails_6_1.lock, contrib/ruby_event_store-protobuf/Gemfile.rails_7_0.lock, contrib/ruby_event_store-sidekiq_scheduler/Gemfile.lock, contrib/ruby_event_store-sidekiq_scheduler/Gemfile.sidekiq_5_2.lock, contrib/ruby_event_store-sidekiq_scheduler/Gemfile.sidekiq_6_5.lock, rails_event_store/Gemfile.lock, rails_event_store/Gemfile.rails_6_0.lock, rails_event_store/Gemfile.rails_6_1.lock, rails_event_store/Gemfile.rails_7_0.lock, rails_event_store/spec/dummy_6_0/Gemfile.lock, rails_event_store/spec/dummy_6_1/Gemfile.lock, rails_event_store/spec/dummy_7_0/Gemfile.lock, rails_event_store/spec/dummy_7_1/Gemfile.lock, ruby_event_store-rspec/Gemfile.lock
In #1719 `base64`` was added as a dependency to `aggregate_root` to prevent warnings/errors in Ruby 3.3/3.4
However there is only one require and no usages of `base64` so it can just be removed.
=> Remove dependency on base64 gem

ruby_event_store-active_record/lib/ruby_event_store/active_record/generators/templates/create_event_store_events_template.erb, ruby_event_store-active_record/lib/ruby_event_store/active_record/generators/templates/mysql/create_event_store_events_template.erb, ruby_event_store-active_record/lib/ruby_event_store/active_record/generators/templates/postgres/create_event_store_events_template.erb, ruby_event_store-active_record/spec/migration_test_spec.rb
https://github.com/RailsEventStore/rails_event_store/issues/1755
=> Prefer migration DSL that calms down strong_migrations

railseventstore.org/docs/core-concepts/request-metadata.md
This page https://railseventstore.org/docs/core-concepts/request-metadata had a broken link to installation page. I fixed it by using a similar link approach a working link is using on https://railseventstore.org/docs/core-concepts/browser page:
https://github.com/RailsEventStore/rails_event_store/blob/d8a68272e0564b6c86928e515cececb5fd07c1a6/railseventstore.org/docs/core-concepts/browser.md?plain=1#L19
=> Docs: Fix broken link to installation page

contrib/ruby_event_store-outbox/CHANGELOG.md, contrib/ruby_event_store-outbox/Gemfile.lock, contrib/ruby_event_store-outbox/Gemfile.rails_7_0.lock, contrib/ruby_event_store-outbox/Gemfile.rails_7_1.lock, contrib/ruby_event_store-outbox/Gemfile.rails_7_2.lock, contrib/ruby_event_store-outbox/Gemfile.sidekiq_6_5.lock, contrib/ruby_event_store-outbox/bin/res_outbox, contrib/ruby_event_store-outbox/lib/ruby_event_store/outbox/version.rb
Lock wait timeouts were causing
```
uninitialized constant RubyEventStore::Outbox::Consumer::RetriableError (NameError)
rescue RetriableError => error
^^^^^^^^^^^^^^
```
=> Outbox require issue

contrib/ruby_event_store-outbox/CHANGELOG.md, contrib/ruby_event_store-outbox/lib/ruby_event_store/outbox/sidekiq_processor.rb, contrib/ruby_event_store-outbox/spec/consumer_spec.rb
This allows Sidekiq to calculate the latency including the time a job has spent in outbox
=> Use record `created_at` as `enqueued_at` timestamp when pushing a job to Sidekiq

ruby_event_store/lib/ruby_event_store/broker.rb, ruby_event_store/lib/ruby_event_store/client.rb, ruby_event_store/lib/ruby_event_store/instrumented_broker.rb, ruby_event_store/lib/ruby_event_store/spec/broker_lint.rb, ruby_event_store/lib/ruby_event_store/subscriptions.rb, ruby_event_store/spec/client_subscriptions_spec.rb, ruby_event_store/spec/instrumented_broker_spec.rb
Currently we always use event type as a topic to which events are published.
This PR allows developer to explicite specify topic.
If it is not specified (default behaviour) the event type is used as it is now (no breaking changes).
=> Use topics

rails_event_store/lib/rails_event_store/async_handler_helpers.rb, rails_event_store/spec/async_handler_helpers_spec.rb
Figure out ways to unbreak `AJ.peform_now(payload)`
=> ActiveJob.perform_now(event) as a valid API to use when AsyncHandler is mixed in

ruby_event_store-active_record/lib/ruby_event_store/active_record.rb, ruby_event_store-active_record/lib/ruby_event_store/active_record/event_repository.rb, ruby_event_store-active_record/lib/ruby_event_store/active_record/railtie.rb
Reason:
https://github.com/rails/rails/issues/31285
In short:
* when in Rails, let Rails load the models after it loads ActiveRecord
itself
* when not Rails, proceed as usual
=> Delay loading ActiveRecord::Base for Rails

ruby_event_store-browser/elm/src/BrowserTime.elm
I'm finding it difficult to read little-endian datetime formats in the events browser. ISO 8601 is the most universally recognized standard that is locale-agnostic.
This PR updates the formatting logic for Rails Events Browser to use ISO 8601.
=> Update browser time to follow ISO 8601 standard
